service: "lambda"
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  subscriptions:
    handler: src/subscriptions/index.handler
    events:
      - httpApi:
          path: /fhir/subscriptions/{endpoint+}
          method: post
      - httpApi:
          path: /fhir/subscriptions/{endpoint+}
          method: put

plugins:
  - serverless-esbuild
  - serverless-offline

# Plugin configuration to prevent duplication issues
pluginLoadOrder:
  - serverless-esbuild
  - serverless-offline

# Disable validation that can cause plugin conflicts in CI
configValidationMode: off
variablesResolutionMode: 20210326

custom:
  esbuild:
    format: esm
    outputFileExtension: .mjs
    packager: pnpm
  serverless-offline:
    httpPort: 6000
    host: 0.0.0.0
