/**
 * Narrative generators for r4b/4.3.0
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
import { AnyDomainResource, Narrative } from "./fhir-types.codegen";
import { DefaultFormatter, Formatter } from "./formatters";
import { startCase } from "./lang-utils";

/** FHIR Type, attribute name, isArray? */
export type NarrativeItemGenerator = [string, string, boolean];

export type NarrativeGenerator =
  | NarrativeItemGenerator[]
  | ((resource: any) => Narrative | string);

export const NARRATIVE_GENERATORS: Record<string, NarrativeGenerator> = {
  Account: [
    ["string", "description", false],
    ["Identifier", "identifier", true],
    ["string", "name", false],
    ["Reference", "owner", false],
    ["Period", "servicePeriod", false],
    ["code", "status", false],
    ["Reference", "subject", true],
    ["CodeableConcept", "type", false],
  ],
  ActivityDefinition: [
    ["CodeableConcept", "code", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["boolean", "doNotPerform", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["code", "kind", false],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  AdministrableProductDefinition: [
    ["CodeableConcept", "administrableDoseForm", false],
    ["Reference", "device", false],
    ["Reference", "formOf", true],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "ingredient", true],
    ["Reference", "producedFrom", true],
    ["code", "status", false],
    ["CodeableConcept", "unitOfPresentation", false],
  ],
  AdverseEvent: [
    ["code", "actuality", false],
    ["CodeableConcept", "category", true],
    ["Reference", "contributor", true],
    ["dateTime", "date", false],
    ["dateTime", "detected", false],
    ["Reference", "encounter", false],
    ["CodeableConcept", "event", false],
    ["Identifier", "identifier", false],
    ["Reference", "location", false],
    ["CodeableConcept", "outcome", false],
    ["dateTime", "recordedDate", false],
    ["Reference", "recorder", false],
    ["Reference", "referenceDocument", true],
    ["Reference", "resultingCondition", true],
    ["CodeableConcept", "seriousness", false],
    ["CodeableConcept", "severity", false],
    ["Reference", "study", true],
    ["Reference", "subject", false],
    ["Reference", "subjectMedicalHistory", true],
  ],
  AllergyIntolerance: [
    ["Reference", "asserter", false],
    ["code", "category", true],
    ["CodeableConcept", "clinicalStatus", false],
    ["CodeableConcept", "code", false],
    ["code", "criticality", false],
    ["Identifier", "identifier", true],
    ["Reference", "patient", false],
    ["code", "type", false],
    ["CodeableConcept", "verificationStatus", false],
  ],
  Appointment: [
    ["CodeableConcept", "appointmentType", false],
    ["CodeableConcept", "cancelationReason", false],
    ["instant", "end", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "reasonCode", true],
    ["CodeableConcept", "serviceCategory", true],
    ["CodeableConcept", "serviceType", true],
    ["CodeableConcept", "specialty", true],
    ["instant", "start", false],
    ["code", "status", false],
  ],
  AppointmentResponse: [
    ["Reference", "actor", false],
    ["Reference", "appointment", false],
    ["Identifier", "identifier", true],
    ["code", "participantStatus", false],
    ["CodeableConcept", "participantType", true],
  ],
  AuditEvent: [
    ["code", "action", false],
    ["code", "outcome", false],
    ["string", "outcomeDesc", false],
    ["CodeableConcept", "purposeOfEvent", true],
    ["instant", "recorded", false],
    ["Coding", "subtype", true],
    ["Coding", "type", false],
  ],
  Basic: [
    ["Reference", "author", false],
    ["CodeableConcept", "code", false],
    ["date", "created", false],
    ["Identifier", "identifier", true],
    ["Reference", "subject", false],
  ],
  BiologicallyDerivedProduct: [["Identifier", "identifier", true]],
  BodyStructure: [
    ["boolean", "active", false],
    ["string", "description", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "location", false],
    ["CodeableConcept", "morphology", false],
    ["Reference", "patient", false],
  ],
  CapabilityStatement: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["code", "fhirVersion", false],
    ["code", "format", true],
    ["canonical", "implementationGuide", true],
    ["canonical", "imports", true],
    ["canonical", "instantiates", true],
    ["CodeableConcept", "jurisdiction", true],
    ["code", "kind", false],
    ["string", "name", false],
    ["code", "patchFormat", true],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  CarePlan: [
    ["Reference", "addresses", true],
    ["Reference", "author", false],
    ["Reference", "basedOn", true],
    ["CodeableConcept", "category", true],
    ["dateTime", "created", false],
    ["string", "description", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["code", "intent", false],
    ["Reference", "partOf", true],
    ["Period", "period", false],
    ["Reference", "replaces", true],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["string", "title", false],
  ],
  CareTeam: [
    ["CodeableConcept", "category", true],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["Reference", "managingOrganization", true],
    ["string", "name", false],
    ["Period", "period", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  CatalogEntry: [
    ["Identifier", "identifier", true],
    ["boolean", "orderable", false],
    ["Reference", "referencedItem", false],
  ],
  ChargeItem: [
    ["Reference", "account", true],
    ["CodeableConcept", "bodysite", true],
    ["CodeableConcept", "code", false],
    ["Reference", "context", false],
    ["dateTime", "enteredDate", false],
    ["Reference", "enterer", false],
    ["Identifier", "identifier", true],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["Timing", "occurrenceTiming", false],
    ["Quantity", "quantity", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  ChargeItemDefinition: [
    ["CodeableConcept", "code", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["uri", "derivedFromUri", true],
    ["markdown", "description", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["canonical", "partOf", true],
    ["string", "publisher", false],
    ["canonical", "replaces", true],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  Citation: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  Claim: [
    ["Period", "billablePeriod", false],
    ["dateTime", "created", false],
    ["Reference", "insurer", false],
    ["Reference", "patient", false],
    ["CodeableConcept", "priority", false],
    ["Reference", "provider", false],
    ["code", "status", false],
    ["CodeableConcept", "type", false],
    ["code", "use", false],
  ],
  ClaimResponse: [
    ["dateTime", "created", false],
    ["Reference", "insurer", false],
    ["code", "outcome", false],
    ["Reference", "patient", false],
    ["Reference", "request", false],
    ["code", "status", false],
    ["CodeableConcept", "type", false],
    ["code", "use", false],
  ],
  ClinicalImpression: [
    ["Reference", "assessor", false],
    ["CodeableConcept", "code", false],
    ["dateTime", "date", false],
    ["string", "description", false],
    ["dateTime", "effectiveDateTime", false],
    ["Period", "effectivePeriod", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["Reference", "problem", true],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  ClinicalUseDefinition: [
    ["CodeableConcept", "category", true],
    ["Identifier", "identifier", true],
    ["Reference", "population", true],
    ["CodeableConcept", "status", false],
    ["Reference", "subject", true],
    ["code", "type", false],
  ],
  CodeSystem: [
    ["boolean", "caseSensitive", false],
    ["boolean", "compositional", false],
    ["ContactDetail", "contact", true],
    ["code", "content", false],
    ["unsignedInt", "count", false],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["code", "hierarchyMeaning", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["canonical", "supplements", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["canonical", "valueSet", false],
    ["string", "version", false],
    ["boolean", "versionNeeded", false],
  ],
  Communication: [
    ["Reference", "basedOn", true],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["Reference", "partOf", true],
    ["code", "priority", false],
    ["CodeableConcept", "reasonCode", true],
    ["Reference", "reasonReference", true],
    ["code", "status", false],
    ["CodeableConcept", "statusReason", false],
    ["Reference", "subject", false],
  ],
  CommunicationRequest: [
    ["dateTime", "authoredOn", false],
    ["Reference", "basedOn", true],
    ["boolean", "doNotPerform", false],
    ["Reference", "encounter", false],
    ["Identifier", "groupIdentifier", false],
    ["Identifier", "identifier", true],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["code", "priority", false],
    ["CodeableConcept", "reasonCode", true],
    ["Reference", "reasonReference", true],
    ["Reference", "replaces", true],
    ["Reference", "requester", false],
    ["Reference", "sender", false],
    ["code", "status", false],
  ],
  CompartmentDefinition: [
    ["code", "code", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["string", "name", false],
    ["string", "publisher", false],
    ["boolean", "search", false],
    ["code", "status", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  Composition: [
    ["Reference", "author", true],
    ["CodeableConcept", "category", true],
    ["code", "confidentiality", false],
    ["Reference", "custodian", false],
    ["dateTime", "date", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", false],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["string", "title", false],
    ["CodeableConcept", "type", false],
  ],
  ConceptMap: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", false],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["uri", "sourceUri", false],
    ["canonical", "sourceCanonical", false],
    ["code", "status", false],
    ["uri", "targetUri", false],
    ["canonical", "targetCanonical", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  Condition: [
    ["Reference", "asserter", false],
    ["CodeableConcept", "bodySite", true],
    ["CodeableConcept", "clinicalStatus", false],
    ["CodeableConcept", "code", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["dateTime", "onsetDateTime", false],
    ["Age", "onsetAge", false],
    ["Period", "onsetPeriod", false],
    ["Range", "onsetRange", false],
    ["string", "onsetString", false],
    ["dateTime", "recordedDate", false],
    ["Reference", "recorder", false],
    ["Reference", "subject", false],
    ["CodeableConcept", "verificationStatus", false],
  ],
  Consent: [
    ["CodeableConcept", "category", true],
    ["dateTime", "dateTime", false],
    ["Identifier", "identifier", true],
    ["Reference", "organization", true],
    ["Reference", "patient", false],
    ["Reference", "performer", true],
    ["CodeableConcept", "policyRule", false],
    ["CodeableConcept", "scope", false],
    ["Attachment", "sourceAttachment", false],
    ["Reference", "sourceReference", false],
    ["code", "status", false],
  ],
  Contract: [
    ["Period", "applies", false],
    ["Identifier", "identifier", true],
    ["dateTime", "issued", false],
    ["string", "name", false],
    ["code", "status", false],
    ["Reference", "subject", true],
    ["CodeableConcept", "subType", true],
    ["string", "title", false],
    ["CodeableConcept", "type", false],
    ["string", "version", false],
  ],
  Coverage: [
    ["Reference", "beneficiary", false],
    ["string", "dependent", false],
    ["Identifier", "identifier", true],
    ["string", "network", false],
    ["positiveInt", "order", false],
    ["Reference", "payor", true],
    ["Period", "period", false],
    ["Reference", "policyHolder", false],
    ["code", "status", false],
    ["Reference", "subscriber", false],
    ["string", "subscriberId", false],
    ["CodeableConcept", "type", false],
  ],
  CoverageEligibilityRequest: [
    ["dateTime", "created", false],
    ["Reference", "insurer", false],
    ["Reference", "patient", false],
    ["code", "purpose", true],
    ["code", "status", false],
  ],
  CoverageEligibilityResponse: [
    ["dateTime", "created", false],
    ["Reference", "insurer", false],
    ["code", "outcome", false],
    ["Reference", "patient", false],
    ["code", "purpose", true],
    ["Reference", "request", false],
    ["code", "status", false],
  ],
  DetectedIssue: [
    ["Reference", "author", false],
    ["CodeableConcept", "code", false],
    ["dateTime", "identifiedDateTime", false],
    ["Period", "identifiedPeriod", false],
    ["Identifier", "identifier", true],
    ["Reference", "implicated", true],
    ["Reference", "patient", false],
    ["code", "severity", false],
    ["code", "status", false],
  ],
  Device: [
    ["CodeableConcept", "safety", true],
    ["code", "status", false],
  ],
  DeviceDefinition: [
    ["Reference", "parentDevice", false],
    ["CodeableConcept", "safety", true],
  ],
  DeviceMetric: [
    ["code", "category", false],
    ["code", "color", false],
    ["Identifier", "identifier", true],
    ["Timing", "measurementPeriod", false],
    ["code", "operationalStatus", false],
    ["Reference", "parent", false],
    ["Reference", "source", false],
    ["CodeableConcept", "type", false],
    ["CodeableConcept", "unit", false],
  ],
  DeviceRequest: [
    ["dateTime", "authoredOn", false],
    ["Reference", "basedOn", true],
    ["Reference", "codeReference", false],
    ["CodeableConcept", "codeCodeableConcept", false],
    ["Reference", "encounter", false],
    ["Identifier", "groupIdentifier", false],
    ["Identifier", "identifier", true],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["code", "intent", false],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["Timing", "occurrenceTiming", false],
    ["Reference", "performer", false],
    ["CodeableConcept", "performerType", false],
    ["code", "priority", false],
    ["Reference", "priorRequest", true],
    ["CodeableConcept", "reasonCode", true],
    ["Reference", "reasonReference", true],
    ["Reference", "requester", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  DeviceUseStatement: [
    ["Reference", "basedOn", true],
    ["CodeableConcept", "bodySite", false],
    ["Reference", "derivedFrom", true],
    ["Reference", "device", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "reasonCode", true],
    ["Reference", "reasonReference", true],
    ["dateTime", "recordedOn", false],
    ["Reference", "source", false],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["Timing", "timingTiming", false],
    ["Period", "timingPeriod", false],
    ["dateTime", "timingDateTime", false],
  ],
  DiagnosticReport: [
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "code", false],
    ["dateTime", "effectiveDateTime", false],
    ["Period", "effectivePeriod", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["instant", "issued", false],
    ["Reference", "performer", true],
    ["Reference", "resultsInterpreter", true],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  DocumentManifest: [
    ["Reference", "author", true],
    ["Reference", "content", true],
    ["string", "description", false],
    ["Identifier", "identifier", true],
    ["Identifier", "masterIdentifier", false],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["CodeableConcept", "type", false],
  ],
  DocumentReference: [
    ["Reference", "author", true],
    ["CodeableConcept", "category", true],
    ["instant", "date", false],
    ["string", "description", false],
    ["code", "docStatus", false],
    ["Identifier", "identifier", true],
    ["Identifier", "masterIdentifier", false],
    ["CodeableConcept", "securityLabel", true],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["CodeableConcept", "type", false],
  ],
  Encounter: [
    ["Reference", "appointment", true],
    ["Coding", "class", false],
    ["Reference", "episodeOfCare", true],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "reasonCode", true],
    ["Reference", "reasonReference", true],
    ["CodeableConcept", "serviceType", false],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["CodeableConcept", "type", true],
  ],
  Endpoint: [
    ["url", "address", false],
    ["Coding", "connectionType", false],
    ["Identifier", "identifier", true],
    ["Reference", "managingOrganization", false],
    ["string", "name", false],
    ["code", "payloadMimeType", true],
    ["CodeableConcept", "payloadType", true],
    ["Period", "period", false],
    ["code", "status", false],
  ],
  EnrollmentRequest: [["code", "status", false]],
  EnrollmentResponse: [["code", "status", false]],
  EpisodeOfCare: [
    ["Reference", "managingOrganization", false],
    ["Reference", "patient", false],
    ["Period", "period", false],
    ["code", "status", false],
    ["CodeableConcept", "type", true],
  ],
  EventDefinition: [
    ["date", "approvalDate", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["date", "lastReviewDate", false],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["TriggerDefinition", "trigger", true],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  Evidence: [
    ["ContactDetail", "author", true],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["ContactDetail", "endorser", true],
    ["Identifier", "identifier", true],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  EvidenceReport: [
    ["ContactDetail", "author", true],
    ["ContactDetail", "contact", true],
    ["ContactDetail", "endorser", true],
    ["Identifier", "identifier", true],
    ["string", "publisher", false],
    ["Identifier", "relatedIdentifier", true],
    ["code", "status", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
  ],
  EvidenceVariable: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["code", "handling", false],
    ["Identifier", "identifier", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["string", "shortTitle", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  ExampleScenario: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  ExplanationOfBenefit: [
    ["Period", "billablePeriod", false],
    ["dateTime", "created", false],
    ["Reference", "insurer", false],
    ["code", "outcome", false],
    ["Reference", "patient", false],
    ["Reference", "provider", false],
    ["code", "status", false],
    ["CodeableConcept", "type", false],
    ["code", "use", false],
  ],
  FamilyMemberHistory: [
    ["Age", "ageAge", false],
    ["Range", "ageRange", false],
    ["string", "ageString", false],
    ["CodeableConcept", "dataAbsentReason", false],
    ["dateTime", "date", false],
    ["boolean", "deceasedBoolean", false],
    ["Age", "deceasedAge", false],
    ["Range", "deceasedRange", false],
    ["date", "deceasedDate", false],
    ["string", "deceasedString", false],
    ["boolean", "estimatedAge", false],
    ["Identifier", "identifier", true],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["string", "name", false],
    ["Reference", "patient", false],
    ["CodeableConcept", "reasonCode", true],
    ["Reference", "reasonReference", true],
    ["CodeableConcept", "relationship", false],
    ["CodeableConcept", "sex", false],
    ["code", "status", false],
  ],
  Flag: [
    ["Reference", "author", false],
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "code", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["Period", "period", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  Goal: [
    ["CodeableConcept", "achievementStatus", false],
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "description", false],
    ["Reference", "expressedBy", false],
    ["code", "lifecycleStatus", false],
    ["CodeableConcept", "priority", false],
    ["date", "startDate", false],
    ["CodeableConcept", "startCodeableConcept", false],
    ["date", "statusDate", false],
    ["Reference", "subject", false],
  ],
  GraphDefinition: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "start", false],
    ["code", "status", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  Group: [
    ["boolean", "active", false],
    ["boolean", "actual", false],
    ["CodeableConcept", "code", false],
    ["Identifier", "identifier", true],
    ["Reference", "managingEntity", false],
    ["string", "name", false],
    ["unsignedInt", "quantity", false],
    ["code", "type", false],
  ],
  GuidanceResponse: [
    ["Identifier", "identifier", true],
    ["uri", "moduleUri", false],
    ["canonical", "moduleCanonical", false],
    ["CodeableConcept", "moduleCodeableConcept", false],
    ["Identifier", "requestIdentifier", false],
    ["code", "status", false],
  ],
  HealthcareService: [
    ["boolean", "active", false],
    ["CodeableConcept", "category", true],
    ["string", "comment", false],
    ["Identifier", "identifier", true],
    ["Reference", "location", true],
    ["string", "name", false],
    ["Attachment", "photo", false],
    ["Reference", "providedBy", false],
    ["CodeableConcept", "specialty", true],
    ["CodeableConcept", "type", true],
  ],
  ImagingStudy: [
    ["Reference", "basedOn", true],
    ["string", "description", false],
    ["Reference", "encounter", false],
    ["Reference", "endpoint", true],
    ["Identifier", "identifier", true],
    ["Reference", "interpreter", true],
    ["Reference", "location", false],
    ["Coding", "modality", true],
    ["Annotation", "note", true],
    ["unsignedInt", "numberOfInstances", false],
    ["unsignedInt", "numberOfSeries", false],
    ["CodeableConcept", "procedureCode", true],
    ["Reference", "procedureReference", false],
    ["CodeableConcept", "reasonCode", true],
    ["Reference", "reasonReference", true],
    ["Reference", "referrer", false],
    ["dateTime", "started", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  Immunization: [
    ["boolean", "isSubpotent", false],
    ["Annotation", "note", true],
    ["dateTime", "occurrenceDateTime", false],
    ["string", "occurrenceString", false],
    ["Reference", "patient", false],
    ["boolean", "primarySource", false],
    ["code", "status", false],
    ["CodeableConcept", "vaccineCode", false],
  ],
  ImmunizationEvaluation: [
    ["CodeableConcept", "doseStatus", false],
    ["Reference", "immunizationEvent", false],
    ["Reference", "patient", false],
    ["code", "status", false],
    ["CodeableConcept", "targetDisease", false],
  ],
  ImmunizationRecommendation: [
    ["dateTime", "date", false],
    ["Identifier", "identifier", true],
    ["Reference", "patient", false],
  ],
  ImplementationGuide: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["code", "fhirVersion", true],
    ["CodeableConcept", "jurisdiction", true],
    ["code", "license", false],
    ["string", "name", false],
    ["id", "packageId", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  Ingredient: [
    ["boolean", "allergenicIndicator", false],
    ["Reference", "for", true],
    ["CodeableConcept", "function", true],
    ["Identifier", "identifier", false],
    ["CodeableConcept", "role", false],
    ["code", "status", false],
  ],
  InsurancePlan: [
    ["Reference", "administeredBy", false],
    ["Reference", "coverageArea", true],
    ["Identifier", "identifier", true],
    ["string", "name", false],
    ["Reference", "ownedBy", false],
    ["code", "status", false],
    ["CodeableConcept", "type", true],
  ],
  Invoice: [
    ["dateTime", "date", false],
    ["Identifier", "identifier", true],
    ["Reference", "recipient", false],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["Money", "totalGross", false],
    ["Money", "totalNet", false],
    ["CodeableConcept", "type", false],
  ],
  Library: [
    ["ContactDetail", "contact", true],
    ["Attachment", "content", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["CodeableConcept", "type", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  Linkage: [
    ["boolean", "active", false],
    ["Reference", "author", false],
  ],
  List: [
    ["CodeableConcept", "code", false],
    ["dateTime", "date", false],
    ["code", "mode", false],
    ["Reference", "source", false],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["string", "title", false],
  ],
  Location: [
    ["string", "description", false],
    ["Identifier", "identifier", true],
    ["Reference", "managingOrganization", false],
    ["code", "mode", false],
    ["string", "name", false],
    ["Coding", "operationalStatus", false],
    ["CodeableConcept", "physicalType", false],
    ["code", "status", false],
    ["CodeableConcept", "type", true],
  ],
  ManufacturedItemDefinition: [
    ["Identifier", "identifier", true],
    ["CodeableConcept", "ingredient", true],
    ["CodeableConcept", "manufacturedDoseForm", false],
    ["Reference", "manufacturer", true],
    ["code", "status", false],
    ["CodeableConcept", "unitOfPresentation", false],
  ],
  Measure: [
    ["markdown", "clinicalRecommendationStatement", false],
    ["CodeableConcept", "compositeScoring", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["markdown", "definition", true],
    ["markdown", "description", false],
    ["markdown", "disclaimer", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["markdown", "guidance", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "improvementNotation", false],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["string", "rateAggregation", false],
    ["markdown", "rationale", false],
    ["string", "riskAdjustment", false],
    ["CodeableConcept", "scoring", false],
    ["code", "status", false],
    ["string", "title", false],
    ["CodeableConcept", "type", true],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  MeasureReport: [
    ["dateTime", "date", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "improvementNotation", false],
    ["canonical", "measure", false],
    ["Period", "period", false],
    ["Reference", "reporter", false],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["code", "type", false],
  ],
  Media: [
    ["Reference", "basedOn", true],
    ["CodeableConcept", "bodySite", false],
    ["Attachment", "content", false],
    ["dateTime", "createdDateTime", false],
    ["Period", "createdPeriod", false],
    ["Reference", "device", false],
    ["string", "deviceName", false],
    ["decimal", "duration", false],
    ["Reference", "encounter", false],
    ["positiveInt", "frames", false],
    ["positiveInt", "height", false],
    ["Identifier", "identifier", true],
    ["instant", "issued", false],
    ["CodeableConcept", "modality", false],
    ["Reference", "operator", false],
    ["Reference", "partOf", true],
    ["CodeableConcept", "reasonCode", true],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["CodeableConcept", "type", false],
    ["CodeableConcept", "view", false],
    ["positiveInt", "width", false],
  ],
  Medication: [
    ["Ratio", "amount", false],
    ["CodeableConcept", "code", false],
    ["Identifier", "identifier", true],
    ["Reference", "manufacturer", false],
    ["code", "status", false],
  ],
  MedicationAdministration: [
    ["dateTime", "effectiveDateTime", false],
    ["Period", "effectivePeriod", false],
    ["uri", "instantiates", true],
    ["CodeableConcept", "medicationCodeableConcept", false],
    ["Reference", "medicationReference", false],
    ["Reference", "partOf", true],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  MedicationDispense: [
    ["CodeableConcept", "medicationCodeableConcept", false],
    ["Reference", "medicationReference", false],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["dateTime", "whenPrepared", false],
  ],
  MedicationKnowledge: [
    ["Quantity", "amount", false],
    ["CodeableConcept", "code", false],
    ["Reference", "manufacturer", false],
    ["code", "status", false],
    ["string", "synonym", true],
  ],
  MedicationRequest: [
    ["dateTime", "authoredOn", false],
    ["Reference", "basedOn", true],
    ["boolean", "doNotPerform", false],
    ["Identifier", "groupIdentifier", false],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["code", "intent", false],
    ["CodeableConcept", "medicationCodeableConcept", false],
    ["Reference", "medicationReference", false],
    ["CodeableConcept", "performerType", false],
    ["code", "priority", false],
    ["boolean", "reportedBoolean", false],
    ["Reference", "reportedReference", false],
    ["Reference", "requester", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  MedicationStatement: [
    ["Reference", "basedOn", true],
    ["CodeableConcept", "category", false],
    ["Reference", "context", false],
    ["dateTime", "dateAsserted", false],
    ["dateTime", "effectiveDateTime", false],
    ["Period", "effectivePeriod", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "medicationCodeableConcept", false],
    ["Reference", "medicationReference", false],
    ["Reference", "partOf", true],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  MedicinalProductDefinition: [
    ["CodeableConcept", "additionalMonitoringIndicator", false],
    ["Reference", "attachedDocument", true],
    ["CodeableConcept", "classification", true],
    ["Reference", "clinicalTrial", true],
    ["Coding", "code", true],
    ["CodeableConcept", "combinedPharmaceuticalDoseForm", false],
    ["markdown", "description", false],
    ["CodeableConcept", "domain", false],
    ["Identifier", "identifier", true],
    ["CodeableReference", "impurity", true],
    ["markdown", "indication", false],
    ["CodeableConcept", "ingredient", true],
    ["CodeableConcept", "legalStatusOfSupply", false],
    ["MarketingStatus", "marketingStatus", true],
    ["Reference", "masterFile", true],
    ["CodeableConcept", "packagedMedicinalProduct", true],
    ["CodeableConcept", "pediatricUseIndicator", false],
    ["CodeableConcept", "route", true],
    ["CodeableConcept", "specialMeasures", true],
    ["CodeableConcept", "status", false],
    ["dateTime", "statusDate", false],
    ["CodeableConcept", "type", false],
    ["string", "version", false],
  ],
  MessageDefinition: [
    ["canonical", "base", false],
    ["code", "category", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["Coding", "eventCoding", false],
    ["uri", "eventUri", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["canonical", "parent", true],
    ["string", "publisher", false],
    ["markdown", "purpose", false],
    ["canonical", "replaces", true],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  MessageHeader: [
    ["Reference", "author", false],
    ["canonical", "definition", false],
    ["Reference", "enterer", false],
    ["Coding", "eventCoding", false],
    ["uri", "eventUri", false],
    ["Reference", "focus", true],
    ["CodeableConcept", "reason", false],
    ["Reference", "responsible", false],
    ["Reference", "sender", false],
  ],
  MolecularSequence: [
    ["integer", "coordinateSystem", false],
    ["Reference", "device", false],
    ["Identifier", "identifier", true],
    ["string", "observedSeq", false],
    ["Reference", "patient", false],
    ["Reference", "performer", false],
    ["Reference", "pointer", true],
    ["Quantity", "quantity", false],
    ["integer", "readCoverage", false],
    ["Reference", "specimen", false],
    ["code", "type", false],
  ],
  NamingSystem: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["CodeableConcept", "jurisdiction", true],
    ["code", "kind", false],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["UsageContext", "useContext", true],
  ],
  NutritionOrder: [
    ["dateTime", "dateTime", false],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["code", "intent", false],
    ["Reference", "orderer", false],
    ["Reference", "patient", false],
    ["code", "status", false],
  ],
  NutritionProduct: [
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "code", false],
    ["Reference", "manufacturer", true],
    ["code", "status", false],
  ],
  Observation: [
    ["Reference", "basedOn", true],
    ["CodeableConcept", "code", false],
    ["Reference", "derivedFrom", true],
    ["dateTime", "effectiveDateTime", false],
    ["Period", "effectivePeriod", false],
    ["Timing", "effectiveTiming", false],
    ["instant", "effectiveInstant", false],
    ["Reference", "encounter", false],
    ["Reference", "focus", true],
    ["Reference", "hasMember", true],
    ["Identifier", "identifier", true],
    ["instant", "issued", false],
    ["Reference", "partOf", true],
    ["Reference", "performer", true],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["Quantity", "valueQuantity", false],
    ["CodeableConcept", "valueCodeableConcept", false],
    ["string", "valueString", false],
    ["boolean", "valueBoolean", false],
    ["integer", "valueInteger", false],
    ["Range", "valueRange", false],
    ["Ratio", "valueRatio", false],
    ["SampledData", "valueSampledData", false],
    ["time", "valueTime", false],
    ["dateTime", "valueDateTime", false],
    ["Period", "valuePeriod", false],
  ],
  ObservationDefinition: [
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "code", false],
    ["Identifier", "identifier", true],
  ],
  OperationDefinition: [
    ["boolean", "affectsState", false],
    ["canonical", "base", false],
    ["code", "code", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["boolean", "instance", false],
    ["CodeableConcept", "jurisdiction", true],
    ["code", "kind", false],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "resource", true],
    ["code", "status", false],
    ["boolean", "system", false],
    ["string", "title", false],
    ["boolean", "type", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  OperationOutcome: [],
  Organization: [
    ["boolean", "active", false],
    ["Identifier", "identifier", true],
    ["string", "name", false],
    ["Reference", "partOf", false],
    ["CodeableConcept", "type", true],
  ],
  OrganizationAffiliation: [
    ["boolean", "active", false],
    ["CodeableConcept", "code", true],
    ["Identifier", "identifier", true],
    ["Reference", "location", true],
    ["Reference", "network", true],
    ["Reference", "organization", false],
    ["Reference", "participatingOrganization", false],
    ["Period", "period", false],
    ["CodeableConcept", "specialty", true],
    ["ContactPoint", "telecom", true],
  ],
  PackagedProductDefinition: [
    ["CodeableConcept", "characteristic", true],
    ["Quantity", "containedItemQuantity", true],
    ["boolean", "copackagedIndicator", false],
    ["markdown", "description", false],
    ["Identifier", "identifier", true],
    ["Reference", "manufacturer", true],
    ["MarketingStatus", "marketingStatus", true],
    ["string", "name", false],
    ["Reference", "packageFor", true],
    ["CodeableConcept", "status", false],
    ["dateTime", "statusDate", false],
    ["CodeableConcept", "type", false],
  ],
  Patient: [
    ["boolean", "active", false],
    ["Address", "address", true],
    ["date", "birthDate", false],
    ["boolean", "deceasedBoolean", false],
    ["dateTime", "deceasedDateTime", false],
    ["code", "gender", false],
    ["Identifier", "identifier", true],
    ["Reference", "managingOrganization", false],
    ["HumanName", "name", true],
    ["ContactPoint", "telecom", true],
  ],
  PaymentNotice: [
    ["Money", "amount", false],
    ["dateTime", "created", false],
    ["Reference", "payment", false],
    ["Reference", "recipient", false],
    ["code", "status", false],
  ],
  PaymentReconciliation: [
    ["dateTime", "created", false],
    ["Money", "paymentAmount", false],
    ["date", "paymentDate", false],
    ["Reference", "paymentIssuer", false],
    ["Period", "period", false],
    ["code", "status", false],
  ],
  Person: [
    ["boolean", "active", false],
    ["date", "birthDate", false],
    ["code", "gender", false],
    ["Reference", "managingOrganization", false],
    ["HumanName", "name", true],
    ["ContactPoint", "telecom", true],
  ],
  PlanDefinition: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["CodeableConcept", "type", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  Practitioner: [
    ["boolean", "active", false],
    ["Address", "address", true],
    ["date", "birthDate", false],
    ["code", "gender", false],
    ["Identifier", "identifier", true],
    ["HumanName", "name", true],
    ["ContactPoint", "telecom", true],
  ],
  PractitionerRole: [
    ["boolean", "active", false],
    ["CodeableConcept", "code", true],
    ["Identifier", "identifier", true],
    ["Reference", "location", true],
    ["Reference", "organization", false],
    ["Period", "period", false],
    ["Reference", "practitioner", false],
    ["CodeableConcept", "specialty", true],
    ["ContactPoint", "telecom", true],
  ],
  Procedure: [
    ["Reference", "asserter", false],
    ["Reference", "basedOn", true],
    ["CodeableConcept", "bodySite", true],
    ["CodeableConcept", "category", false],
    ["CodeableConcept", "code", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["Reference", "location", false],
    ["CodeableConcept", "outcome", false],
    ["Reference", "partOf", true],
    ["dateTime", "performedDateTime", false],
    ["Period", "performedPeriod", false],
    ["string", "performedString", false],
    ["Age", "performedAge", false],
    ["Range", "performedRange", false],
    ["CodeableConcept", "reasonCode", true],
    ["Reference", "reasonReference", true],
    ["Reference", "recorder", false],
    ["code", "status", false],
    ["CodeableConcept", "statusReason", false],
    ["Reference", "subject", false],
  ],
  Provenance: [
    ["instant", "recorded", false],
    ["Reference", "target", true],
  ],
  Questionnaire: [
    ["Coding", "code", true],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["code", "subjectType", true],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  QuestionnaireResponse: [
    ["Reference", "author", false],
    ["dateTime", "authored", false],
    ["Reference", "basedOn", true],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", false],
    ["Reference", "partOf", true],
    ["canonical", "questionnaire", false],
    ["Reference", "source", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  RegulatedAuthorization: [
    ["CodeableConcept", "basis", true],
    ["markdown", "description", false],
    ["Reference", "holder", false],
    ["Identifier", "identifier", true],
    ["CodeableReference", "indication", false],
    ["CodeableConcept", "intendedUse", false],
    ["CodeableConcept", "region", true],
    ["Reference", "regulator", false],
    ["CodeableConcept", "status", false],
    ["dateTime", "statusDate", false],
    ["Reference", "subject", true],
    ["CodeableConcept", "type", false],
    ["Period", "validityPeriod", false],
  ],
  RelatedPerson: [
    ["boolean", "active", false],
    ["Address", "address", true],
    ["date", "birthDate", false],
    ["code", "gender", false],
    ["Identifier", "identifier", true],
    ["HumanName", "name", true],
    ["Reference", "patient", false],
    ["CodeableConcept", "relationship", true],
    ["ContactPoint", "telecom", true],
  ],
  RequestGroup: [
    ["CodeableConcept", "code", false],
    ["Identifier", "groupIdentifier", false],
    ["Identifier", "identifier", true],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["code", "intent", false],
    ["code", "priority", false],
    ["code", "status", false],
  ],
  ResearchDefinition: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Reference", "exposure", false],
    ["Reference", "exposureAlternative", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["Reference", "outcome", false],
    ["Reference", "population", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  ResearchElementDefinition: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["string", "shortTitle", false],
    ["code", "status", false],
    ["string", "title", false],
    ["code", "type", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  ResearchStudy: [
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "condition", true],
    ["ContactDetail", "contact", true],
    ["Reference", "enrollment", true],
    ["CodeableConcept", "focus", true],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "keyword", true],
    ["CodeableConcept", "location", true],
    ["Reference", "partOf", true],
    ["Period", "period", false],
    ["CodeableConcept", "phase", false],
    ["CodeableConcept", "primaryPurposeType", false],
    ["Reference", "principalInvestigator", false],
    ["Reference", "protocol", true],
    ["CodeableConcept", "reasonStopped", false],
    ["Reference", "site", true],
    ["Reference", "sponsor", false],
    ["code", "status", false],
    ["string", "title", false],
  ],
  ResearchSubject: [
    ["Identifier", "identifier", true],
    ["Reference", "individual", false],
    ["Period", "period", false],
    ["code", "status", false],
    ["Reference", "study", false],
  ],
  RiskAssessment: [
    ["CodeableConcept", "code", false],
    ["Reference", "condition", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "method", false],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["Reference", "performer", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  Schedule: [
    ["boolean", "active", false],
    ["Reference", "actor", true],
    ["Identifier", "identifier", true],
    ["Period", "planningHorizon", false],
    ["CodeableConcept", "serviceCategory", true],
    ["CodeableConcept", "serviceType", true],
    ["CodeableConcept", "specialty", true],
  ],
  SearchParameter: [
    ["code", "base", true],
    ["code", "code", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["boolean", "experimental", false],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["code", "type", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  ServiceRequest: [
    ["boolean", "asNeededBoolean", false],
    ["CodeableConcept", "asNeededCodeableConcept", false],
    ["dateTime", "authoredOn", false],
    ["Reference", "basedOn", true],
    ["CodeableConcept", "bodySite", true],
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "code", false],
    ["boolean", "doNotPerform", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["code", "intent", false],
    ["CodeableConcept", "locationCode", true],
    ["Reference", "locationReference", true],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["Timing", "occurrenceTiming", false],
    ["CodeableConcept", "orderDetail", true],
    ["string", "patientInstruction", false],
    ["Reference", "performer", true],
    ["CodeableConcept", "performerType", false],
    ["code", "priority", false],
    ["Quantity", "quantityQuantity", false],
    ["Ratio", "quantityRatio", false],
    ["Range", "quantityRange", false],
    ["CodeableConcept", "reasonCode", true],
    ["Reference", "reasonReference", true],
    ["Reference", "replaces", true],
    ["Reference", "requester", false],
    ["Identifier", "requisition", false],
    ["Reference", "specimen", true],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  Slot: [
    ["CodeableConcept", "appointmentType", false],
    ["instant", "end", false],
    ["Identifier", "identifier", true],
    ["Reference", "schedule", false],
    ["CodeableConcept", "serviceCategory", true],
    ["CodeableConcept", "serviceType", true],
    ["CodeableConcept", "specialty", true],
    ["instant", "start", false],
    ["code", "status", false],
  ],
  Specimen: [
    ["Identifier", "accessionIdentifier", false],
    ["CodeableConcept", "condition", true],
    ["Identifier", "identifier", true],
    ["dateTime", "receivedTime", false],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["CodeableConcept", "type", false],
  ],
  SpecimenDefinition: [
    ["CodeableConcept", "collection", true],
    ["Identifier", "identifier", false],
    ["CodeableConcept", "patientPreparation", true],
    ["string", "timeAspect", false],
    ["CodeableConcept", "typeCollected", false],
  ],
  StructureDefinition: [
    ["boolean", "abstract", false],
    ["canonical", "baseDefinition", false],
    ["ContactDetail", "contact", true],
    ["string", "contextInvariant", true],
    ["dateTime", "date", false],
    ["code", "derivation", false],
    ["boolean", "experimental", false],
    ["code", "fhirVersion", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["Coding", "keyword", true],
    ["code", "kind", false],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "type", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  StructureMap: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["canonical", "import", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  Subscription: [
    ["ContactPoint", "contact", true],
    ["string", "criteria", false],
    ["instant", "end", false],
    ["string", "error", false],
    ["string", "reason", false],
    ["code", "status", false],
  ],
  SubscriptionStatus: [
    ["CodeableConcept", "error", true],
    ["string", "eventsSinceSubscriptionStart", false],
    ["code", "status", false],
    ["Reference", "subscription", false],
    ["canonical", "topic", false],
    ["code", "type", false],
  ],
  SubscriptionTopic: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["canonical", "derivedFrom", true],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  Substance: [
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "code", false],
    ["string", "description", false],
    ["Identifier", "identifier", true],
    ["code", "status", false],
  ],
  SubstanceDefinition: [
    ["CodeableConcept", "classification", true],
    ["markdown", "description", false],
    ["CodeableConcept", "domain", false],
    ["CodeableConcept", "grade", true],
    ["Identifier", "identifier", true],
    ["Reference", "informationSource", true],
    ["Reference", "manufacturer", true],
    ["Annotation", "note", true],
    ["CodeableConcept", "status", false],
    ["Reference", "supplier", true],
    ["string", "version", false],
  ],
  SupplyDelivery: [
    ["Reference", "basedOn", true],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["Timing", "occurrenceTiming", false],
    ["Reference", "partOf", true],
    ["code", "status", false],
  ],
  SupplyRequest: [
    ["dateTime", "authoredOn", false],
    ["CodeableConcept", "category", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "itemCodeableConcept", false],
    ["Reference", "itemReference", false],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["Timing", "occurrenceTiming", false],
    ["code", "priority", false],
    ["Quantity", "quantity", false],
    ["Reference", "requester", false],
    ["code", "status", false],
    ["Reference", "supplier", true],
  ],
  Task: [
    ["Reference", "basedOn", true],
    ["CodeableConcept", "businessStatus", false],
    ["CodeableConcept", "code", false],
    ["string", "description", false],
    ["Reference", "encounter", false],
    ["Period", "executionPeriod", false],
    ["Reference", "focus", false],
    ["Reference", "for", false],
    ["Identifier", "groupIdentifier", false],
    ["canonical", "instantiatesCanonical", false],
    ["uri", "instantiatesUri", false],
    ["code", "intent", false],
    ["dateTime", "lastModified", false],
    ["Reference", "location", false],
    ["Reference", "owner", false],
    ["Reference", "partOf", true],
    ["Reference", "requester", false],
    ["code", "status", false],
    ["CodeableConcept", "statusReason", false],
  ],
  TerminologyCapabilities: [
    ["ContactDetail", "contact", true],
    ["markdown", "copyright", false],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["CodeableConcept", "jurisdiction", true],
    ["code", "kind", false],
    ["boolean", "lockedDate", false],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  TestReport: [
    ["Identifier", "identifier", false],
    ["dateTime", "issued", false],
    ["string", "name", false],
    ["code", "result", false],
    ["decimal", "score", false],
    ["code", "status", false],
    ["string", "tester", false],
    ["Reference", "testScript", false],
  ],
  TestScript: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", false],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  ValueSet: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["boolean", "immutable", false],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  VerificationResult: [
    ["CodeableConcept", "failureAction", false],
    ["CodeableConcept", "need", false],
    ["code", "status", false],
    ["dateTime", "statusDate", false],
    ["Reference", "target", true],
    ["string", "targetLocation", true],
    ["CodeableConcept", "validationProcess", true],
    ["CodeableConcept", "validationType", false],
  ],
  VisionPrescription: [
    ["dateTime", "created", false],
    ["dateTime", "dateWritten", false],
    ["Reference", "patient", false],
    ["Reference", "prescriber", false],
    ["code", "status", false],
  ],
};

export interface NarrativeOptions {
  /** The formatter to use. Will use the `Formatter.default` if not provided. */
  formatter?: DefaultFormatter | null | undefined;
}

export function narrative<TResource extends AnyDomainResource>(
  resource: TResource,
  options?: NarrativeOptions | null | undefined
): Narrative | undefined {
  const generator = NARRATIVE_GENERATORS[resource.resourceType];
  if (!generator) {
    return;
  }

  if (typeof generator === "function") {
    const result = generator(resource);
    if (typeof result === "string") {
      return {
        status: "generated",
        div: result,
      };
    }

    return result;
  }

  return {
    status: "generated",
    div: `<div xmlns="http://www.w3.org/1999/xhtml">${render(
      resource,
      generator,
      options
    )}</div>`,
  };
}

function render(
  item: object,
  components: Array<NarrativeItemGenerator>,
  options: NarrativeOptions | null | undefined
): string {
  const formatter = options?.formatter ?? Formatter.default;

  return `<ul>${components
    .map((component) => {
      const [type, attribute] = component;
      const value = (item as any)[attribute];

      if (value == undefined) {
        return;
      }

      let renderedValue;
      const narrativeGenerator = NARRATIVE_GENERATORS[type];
      if (typeof narrativeGenerator === "function") {
        renderedValue = narrativeGenerator(value);
      } else if (typeof narrativeGenerator === "object") {
        renderedValue = render(value, narrativeGenerator, options);
      } else if (formatter.canFormat(type)) {
        renderedValue = htmlEncode(formatter.format(type, value as never));
      } else {
        return;
      }

      return `<li><span>${startCase(attribute).replace(
        " Boolean",
        ""
      )}: </span>${renderedValue}</li>`;
    })
    .filter(Boolean)
    .join("")}</ul>`;
}

function htmlEncode(value: string): string {
  return value.replace(
    /[&<>\u00A0-\u9999]/g,
    (i) => "&#" + i.codePointAt(0) + ";"
  );
}
