/**
 * Narrative generators for r4b/4.3.0
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
import { AnyDomainResource, Narrative } from "./fhir-types.codegen";
import { DefaultFormatter, Formatter } from "./formatters";
import { startCase } from "./lang-utils";

/** Attribute name, FHIR Type */
export type NarrativeItemGenerator = [string, string];

export type NarrativeGenerator =
  | NarrativeItemGenerator[]
  | ((resource: any) => Narrative | string);

export interface NarrativeOptions {
  /** The formatter to use. Will use the `Formatter.default` if not provided. */
  formatter?: DefaultFormatter | null | undefined;
}

export const NARRATIVE_GENERATORS: Record<string, NarrativeGenerator> = {
  Account: [
    ["coverage", "AccountCoverage"],
    ["description", "string"],
    ["identifier", "Identifier"],
    ["name", "string"],
    ["owner", "Reference"],
    ["servicePeriod", "Period"],
    ["status", "code"],
    ["subject", "Reference"],
    ["type", "CodeableConcept"],
  ],
  AccountCoverage: [
    ["coverage", "Reference"],
    ["modifierExtension", "Extension"],
    ["priority", "positiveInt"],
  ],
  ActivityDefinition: [
    ["code", "CodeableConcept"],
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["description", "markdown"],
    ["doNotPerform", "boolean"],
    ["effectivePeriod", "Period"],
    ["experimental", "boolean"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["kind", "code"],
    ["name", "string"],
    ["publisher", "string"],
    ["status", "code"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  AdministrableProductDefinition: [
    ["administrableDoseForm", "CodeableConcept"],
    ["device", "Reference"],
    ["formOf", "Reference"],
    ["identifier", "Identifier"],
    ["ingredient", "CodeableConcept"],
    ["producedFrom", "Reference"],
    ["property", "AdministrableProductDefinitionProperty"],
    [
      "routeOfAdministration",
      "AdministrableProductDefinitionRouteOfAdministration",
    ],
    ["status", "code"],
    ["unitOfPresentation", "CodeableConcept"],
  ],
  AdministrableProductDefinitionProperty: [
    ["modifierExtension", "Extension"],
    ["status", "CodeableConcept"],
    ["type", "CodeableConcept"],
    ["valueCodeableConcept", "CodeableConcept"],
    ["valueQuantity", "Quantity"],
    ["valueDate", "date"],
    ["valueBoolean", "boolean"],
    ["valueAttachment", "Attachment"],
  ],
  AdministrableProductDefinitionRouteOfAdministration: [
    ["code", "CodeableConcept"],
    ["firstDose", "Quantity"],
    ["maxDosePerDay", "Quantity"],
    ["maxDosePerTreatmentPeriod", "Ratio"],
    ["maxSingleDose", "Quantity"],
    ["maxTreatmentPeriod", "Duration"],
    ["modifierExtension", "Extension"],
    [
      "targetSpecies",
      "AdministrableProductDefinitionRouteOfAdministrationTargetSpecies",
    ],
  ],
  AdministrableProductDefinitionRouteOfAdministrationTargetSpecies: [
    ["code", "CodeableConcept"],
    ["modifierExtension", "Extension"],
    [
      "withdrawalPeriod",
      "AdministrableProductDefinitionRouteOfAdministrationTargetSpeciesWithdrawalPeriod",
    ],
  ],
  AdministrableProductDefinitionRouteOfAdministrationTargetSpeciesWithdrawalPeriod:
    [
      ["modifierExtension", "Extension"],
      ["supportingInformation", "string"],
      ["tissue", "CodeableConcept"],
      ["value", "Quantity"],
    ],
  AdverseEvent: [
    ["actuality", "code"],
    ["category", "CodeableConcept"],
    ["contributor", "Reference"],
    ["date", "dateTime"],
    ["detected", "dateTime"],
    ["encounter", "Reference"],
    ["event", "CodeableConcept"],
    ["identifier", "Identifier"],
    ["location", "Reference"],
    ["outcome", "CodeableConcept"],
    ["recordedDate", "dateTime"],
    ["recorder", "Reference"],
    ["referenceDocument", "Reference"],
    ["resultingCondition", "Reference"],
    ["seriousness", "CodeableConcept"],
    ["severity", "CodeableConcept"],
    ["study", "Reference"],
    ["subject", "Reference"],
    ["subjectMedicalHistory", "Reference"],
    ["suspectEntity", "AdverseEventSuspectEntity"],
  ],
  AdverseEventSuspectEntity: [
    ["causality", "AdverseEventSuspectEntityCausality"],
    ["instance", "Reference"],
    ["modifierExtension", "Extension"],
  ],
  AdverseEventSuspectEntityCausality: [
    ["assessment", "CodeableConcept"],
    ["author", "Reference"],
    ["method", "CodeableConcept"],
    ["modifierExtension", "Extension"],
    ["productRelatedness", "string"],
  ],
  AllergyIntolerance: [
    ["asserter", "Reference"],
    ["category", "code"],
    ["clinicalStatus", "CodeableConcept"],
    ["code", "CodeableConcept"],
    ["criticality", "code"],
    ["identifier", "Identifier"],
    ["patient", "Reference"],
    ["type", "code"],
    ["verificationStatus", "CodeableConcept"],
  ],
  Appointment: [
    ["appointmentType", "CodeableConcept"],
    ["cancelationReason", "CodeableConcept"],
    ["end", "instant"],
    ["identifier", "Identifier"],
    ["reasonCode", "CodeableConcept"],
    ["serviceCategory", "CodeableConcept"],
    ["serviceType", "CodeableConcept"],
    ["specialty", "CodeableConcept"],
    ["start", "instant"],
    ["status", "code"],
  ],
  AppointmentResponse: [
    ["actor", "Reference"],
    ["appointment", "Reference"],
    ["identifier", "Identifier"],
    ["participantStatus", "code"],
    ["participantType", "CodeableConcept"],
  ],
  AuditEvent: [
    ["action", "code"],
    ["outcome", "code"],
    ["outcomeDesc", "string"],
    ["purposeOfEvent", "CodeableConcept"],
    ["recorded", "instant"],
    ["subtype", "Coding"],
    ["type", "Coding"],
  ],
  Basic: [
    ["author", "Reference"],
    ["code", "CodeableConcept"],
    ["created", "date"],
    ["identifier", "Identifier"],
    ["subject", "Reference"],
  ],
  BiologicallyDerivedProduct: [["identifier", "Identifier"]],
  BodyStructure: [
    ["active", "boolean"],
    ["description", "string"],
    ["identifier", "Identifier"],
    ["location", "CodeableConcept"],
    ["morphology", "CodeableConcept"],
    ["patient", "Reference"],
  ],
  CapabilityStatement: [
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["document", "CapabilityStatementDocument"],
    ["experimental", "boolean"],
    ["fhirVersion", "code"],
    ["format", "code"],
    ["implementation", "CapabilityStatementImplementation"],
    ["implementationGuide", "canonical"],
    ["imports", "canonical"],
    ["instantiates", "canonical"],
    ["jurisdiction", "CodeableConcept"],
    ["kind", "code"],
    ["messaging", "CapabilityStatementMessaging"],
    ["name", "string"],
    ["patchFormat", "code"],
    ["publisher", "string"],
    ["rest", "CapabilityStatementRest"],
    ["software", "CapabilityStatementSoftware"],
    ["status", "code"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  CapabilityStatementDocument: [
    ["mode", "code"],
    ["modifierExtension", "Extension"],
    ["profile", "canonical"],
  ],
  CapabilityStatementImplementation: [
    ["custodian", "Reference"],
    ["description", "string"],
    ["modifierExtension", "Extension"],
    ["url", "url"],
  ],
  CapabilityStatementMessaging: [
    ["modifierExtension", "Extension"],
    ["supportedMessage", "CapabilityStatementMessagingSupportedMessage"],
  ],
  CapabilityStatementMessagingSupportedMessage: [
    ["definition", "canonical"],
    ["mode", "code"],
    ["modifierExtension", "Extension"],
  ],
  CapabilityStatementRest: [
    ["mode", "code"],
    ["modifierExtension", "Extension"],
    ["resource", "CapabilityStatementRestResource"],
    ["security", "CapabilityStatementRestSecurity"],
  ],
  CapabilityStatementRestResource: [
    ["modifierExtension", "Extension"],
    ["operation", "CapabilityStatementRestResourceOperation"],
    ["profile", "canonical"],
    ["supportedProfile", "canonical"],
    ["type", "code"],
  ],
  CapabilityStatementRestResourceOperation: [
    ["definition", "canonical"],
    ["modifierExtension", "Extension"],
    ["name", "string"],
  ],
  CapabilityStatementRestSecurity: [
    ["cors", "boolean"],
    ["modifierExtension", "Extension"],
    ["service", "CodeableConcept"],
  ],
  CapabilityStatementSoftware: [
    ["modifierExtension", "Extension"],
    ["name", "string"],
    ["releaseDate", "dateTime"],
    ["version", "string"],
  ],
  CarePlan: [
    ["addresses", "Reference"],
    ["author", "Reference"],
    ["basedOn", "Reference"],
    ["category", "CodeableConcept"],
    ["created", "dateTime"],
    ["description", "string"],
    ["encounter", "Reference"],
    ["identifier", "Identifier"],
    ["instantiatesCanonical", "canonical"],
    ["instantiatesUri", "uri"],
    ["intent", "code"],
    ["partOf", "Reference"],
    ["period", "Period"],
    ["replaces", "Reference"],
    ["status", "code"],
    ["subject", "Reference"],
    ["title", "string"],
  ],
  CareTeam: [
    ["category", "CodeableConcept"],
    ["encounter", "Reference"],
    ["identifier", "Identifier"],
    ["managingOrganization", "Reference"],
    ["name", "string"],
    ["period", "Period"],
    ["status", "code"],
    ["subject", "Reference"],
  ],
  CatalogEntry: [
    ["identifier", "Identifier"],
    ["orderable", "boolean"],
    ["referencedItem", "Reference"],
  ],
  ChargeItem: [
    ["account", "Reference"],
    ["bodysite", "CodeableConcept"],
    ["code", "CodeableConcept"],
    ["context", "Reference"],
    ["enteredDate", "dateTime"],
    ["enterer", "Reference"],
    ["identifier", "Identifier"],
    ["occurrenceDateTime", "dateTime"],
    ["occurrencePeriod", "Period"],
    ["occurrenceTiming", "Timing"],
    ["quantity", "Quantity"],
    ["status", "code"],
    ["subject", "Reference"],
  ],
  ChargeItemDefinition: [
    ["code", "CodeableConcept"],
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["derivedFromUri", "uri"],
    ["description", "markdown"],
    ["effectivePeriod", "Period"],
    ["experimental", "boolean"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["partOf", "canonical"],
    ["publisher", "string"],
    ["replaces", "canonical"],
    ["status", "code"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  Citation: [
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["effectivePeriod", "Period"],
    ["experimental", "boolean"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["publisher", "string"],
    ["status", "code"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  Claim: [
    ["billablePeriod", "Period"],
    ["created", "dateTime"],
    ["insurance", "ClaimInsurance"],
    ["insurer", "Reference"],
    ["patient", "Reference"],
    ["priority", "CodeableConcept"],
    ["provider", "Reference"],
    ["status", "code"],
    ["type", "CodeableConcept"],
    ["use", "code"],
  ],
  ClaimInsurance: [
    ["coverage", "Reference"],
    ["focal", "boolean"],
    ["modifierExtension", "Extension"],
    ["sequence", "positiveInt"],
  ],
  ClaimResponse: [
    ["created", "dateTime"],
    ["insurer", "Reference"],
    ["outcome", "code"],
    ["patient", "Reference"],
    ["request", "Reference"],
    ["status", "code"],
    ["total", "ClaimResponseTotal"],
    ["type", "CodeableConcept"],
    ["use", "code"],
  ],
  ClaimResponseTotal: [
    ["amount", "Money"],
    ["category", "CodeableConcept"],
    ["modifierExtension", "Extension"],
  ],
  ClinicalImpression: [
    ["assessor", "Reference"],
    ["code", "CodeableConcept"],
    ["date", "dateTime"],
    ["description", "string"],
    ["effectiveDateTime", "dateTime"],
    ["effectivePeriod", "Period"],
    ["encounter", "Reference"],
    ["identifier", "Identifier"],
    ["problem", "Reference"],
    ["status", "code"],
    ["subject", "Reference"],
  ],
  ClinicalUseDefinition: [
    ["category", "CodeableConcept"],
    ["contraindication", "ClinicalUseDefinitionContraindication"],
    ["identifier", "Identifier"],
    ["indication", "ClinicalUseDefinitionIndication"],
    ["interaction", "ClinicalUseDefinitionInteraction"],
    ["population", "Reference"],
    ["status", "CodeableConcept"],
    ["subject", "Reference"],
    ["type", "code"],
    ["undesirableEffect", "ClinicalUseDefinitionUndesirableEffect"],
    ["warning", "ClinicalUseDefinitionWarning"],
  ],
  ClinicalUseDefinitionContraindication: [
    ["comorbidity", "CodeableReference"],
    ["diseaseStatus", "CodeableReference"],
    ["diseaseSymptomProcedure", "CodeableReference"],
    ["indication", "Reference"],
    ["modifierExtension", "Extension"],
    ["otherTherapy", "ClinicalUseDefinitionContraindicationOtherTherapy"],
  ],
  ClinicalUseDefinitionContraindicationOtherTherapy: [
    ["modifierExtension", "Extension"],
    ["relationshipType", "CodeableConcept"],
    ["therapy", "CodeableReference"],
  ],
  ClinicalUseDefinitionIndication: [
    ["comorbidity", "CodeableReference"],
    ["diseaseStatus", "CodeableReference"],
    ["diseaseSymptomProcedure", "CodeableReference"],
    ["durationRange", "Range"],
    ["durationString", "string"],
    ["intendedEffect", "CodeableReference"],
    ["modifierExtension", "Extension"],
    ["undesirableEffect", "Reference"],
  ],
  ClinicalUseDefinitionInteraction: [
    ["effect", "CodeableReference"],
    ["incidence", "CodeableConcept"],
    ["interactant", "ClinicalUseDefinitionInteractionInteractant"],
    ["management", "CodeableConcept"],
    ["modifierExtension", "Extension"],
    ["type", "CodeableConcept"],
  ],
  ClinicalUseDefinitionInteractionInteractant: [
    ["itemReference", "Reference"],
    ["itemCodeableConcept", "CodeableConcept"],
    ["modifierExtension", "Extension"],
  ],
  ClinicalUseDefinitionUndesirableEffect: [
    ["classification", "CodeableConcept"],
    ["frequencyOfOccurrence", "CodeableConcept"],
    ["modifierExtension", "Extension"],
    ["symptomConditionEffect", "CodeableReference"],
  ],
  ClinicalUseDefinitionWarning: [
    ["code", "CodeableConcept"],
    ["description", "markdown"],
    ["modifierExtension", "Extension"],
  ],
  CodeSystem: [
    ["caseSensitive", "boolean"],
    ["compositional", "boolean"],
    ["contact", "ContactDetail"],
    ["content", "code"],
    ["count", "unsignedInt"],
    ["date", "dateTime"],
    ["experimental", "boolean"],
    ["filter", "CodeSystemFilter"],
    ["hierarchyMeaning", "code"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["property", "CodeSystemProperty"],
    ["publisher", "string"],
    ["status", "code"],
    ["supplements", "canonical"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["valueSet", "canonical"],
    ["version", "string"],
    ["versionNeeded", "boolean"],
  ],
  CodeSystemFilter: [
    ["code", "code"],
    ["description", "string"],
    ["modifierExtension", "Extension"],
    ["operator", "code"],
    ["value", "string"],
  ],
  CodeSystemProperty: [
    ["code", "code"],
    ["description", "string"],
    ["modifierExtension", "Extension"],
    ["type", "code"],
    ["uri", "uri"],
  ],
  Communication: [
    ["basedOn", "Reference"],
    ["encounter", "Reference"],
    ["identifier", "Identifier"],
    ["instantiatesCanonical", "canonical"],
    ["instantiatesUri", "uri"],
    ["partOf", "Reference"],
    ["priority", "code"],
    ["reasonCode", "CodeableConcept"],
    ["reasonReference", "Reference"],
    ["status", "code"],
    ["statusReason", "CodeableConcept"],
    ["subject", "Reference"],
  ],
  CommunicationRequest: [
    ["authoredOn", "dateTime"],
    ["basedOn", "Reference"],
    ["doNotPerform", "boolean"],
    ["encounter", "Reference"],
    ["groupIdentifier", "Identifier"],
    ["identifier", "Identifier"],
    ["occurrenceDateTime", "dateTime"],
    ["occurrencePeriod", "Period"],
    ["priority", "code"],
    ["reasonCode", "CodeableConcept"],
    ["reasonReference", "Reference"],
    ["replaces", "Reference"],
    ["requester", "Reference"],
    ["sender", "Reference"],
    ["status", "code"],
  ],
  CompartmentDefinition: [
    ["code", "code"],
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["experimental", "boolean"],
    ["name", "string"],
    ["publisher", "string"],
    ["resource", "CompartmentDefinitionResource"],
    ["search", "boolean"],
    ["status", "code"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  CompartmentDefinitionResource: [
    ["code", "code"],
    ["modifierExtension", "Extension"],
    ["param", "string"],
  ],
  Composition: [
    ["author", "Reference"],
    ["category", "CodeableConcept"],
    ["confidentiality", "code"],
    ["custodian", "Reference"],
    ["date", "dateTime"],
    ["encounter", "Reference"],
    ["event", "CompositionEvent"],
    ["identifier", "Identifier"],
    ["status", "code"],
    ["subject", "Reference"],
    ["title", "string"],
    ["type", "CodeableConcept"],
  ],
  CompositionEvent: [
    ["code", "CodeableConcept"],
    ["detail", "Reference"],
    ["modifierExtension", "Extension"],
    ["period", "Period"],
  ],
  ConceptMap: [
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["experimental", "boolean"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["publisher", "string"],
    ["sourceUri", "uri"],
    ["sourceCanonical", "canonical"],
    ["status", "code"],
    ["targetUri", "uri"],
    ["targetCanonical", "canonical"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  Condition: [
    ["asserter", "Reference"],
    ["bodySite", "CodeableConcept"],
    ["clinicalStatus", "CodeableConcept"],
    ["code", "CodeableConcept"],
    ["encounter", "Reference"],
    ["identifier", "Identifier"],
    ["onsetDateTime", "dateTime"],
    ["onsetAge", "Age"],
    ["onsetPeriod", "Period"],
    ["onsetRange", "Range"],
    ["onsetString", "string"],
    ["recordedDate", "dateTime"],
    ["recorder", "Reference"],
    ["subject", "Reference"],
    ["verificationStatus", "CodeableConcept"],
  ],
  Consent: [
    ["category", "CodeableConcept"],
    ["dateTime", "dateTime"],
    ["identifier", "Identifier"],
    ["organization", "Reference"],
    ["patient", "Reference"],
    ["performer", "Reference"],
    ["policyRule", "CodeableConcept"],
    ["provision", "ConsentProvision"],
    ["scope", "CodeableConcept"],
    ["sourceAttachment", "Attachment"],
    ["sourceReference", "Reference"],
    ["status", "code"],
    ["verification", "ConsentVerification"],
  ],
  ConsentProvision: [
    ["action", "CodeableConcept"],
    ["class", "Coding"],
    ["code", "CodeableConcept"],
    ["data", "ConsentProvisionData"],
    ["dataPeriod", "Period"],
    ["modifierExtension", "Extension"],
    ["period", "Period"],
    ["purpose", "Coding"],
    ["securityLabel", "Coding"],
    ["type", "code"],
  ],
  ConsentProvisionData: [
    ["meaning", "code"],
    ["modifierExtension", "Extension"],
    ["reference", "Reference"],
  ],
  ConsentVerification: [
    ["modifierExtension", "Extension"],
    ["verified", "boolean"],
  ],
  Contract: [
    ["applies", "Period"],
    ["identifier", "Identifier"],
    ["issued", "dateTime"],
    ["name", "string"],
    ["status", "code"],
    ["subject", "Reference"],
    ["subType", "CodeableConcept"],
    ["title", "string"],
    ["type", "CodeableConcept"],
    ["version", "string"],
  ],
  Coverage: [
    ["beneficiary", "Reference"],
    ["dependent", "string"],
    ["identifier", "Identifier"],
    ["network", "string"],
    ["order", "positiveInt"],
    ["payor", "Reference"],
    ["period", "Period"],
    ["policyHolder", "Reference"],
    ["status", "code"],
    ["subscriber", "Reference"],
    ["subscriberId", "string"],
    ["type", "CodeableConcept"],
  ],
  CoverageEligibilityRequest: [
    ["created", "dateTime"],
    ["insurer", "Reference"],
    ["patient", "Reference"],
    ["purpose", "code"],
    ["status", "code"],
  ],
  CoverageEligibilityResponse: [
    ["created", "dateTime"],
    ["insurer", "Reference"],
    ["outcome", "code"],
    ["patient", "Reference"],
    ["purpose", "code"],
    ["request", "Reference"],
    ["status", "code"],
  ],
  DetectedIssue: [
    ["author", "Reference"],
    ["code", "CodeableConcept"],
    ["identifiedDateTime", "dateTime"],
    ["identifiedPeriod", "Period"],
    ["identifier", "Identifier"],
    ["implicated", "Reference"],
    ["patient", "Reference"],
    ["severity", "code"],
    ["status", "code"],
  ],
  Device: [
    ["safety", "CodeableConcept"],
    ["status", "code"],
    ["udiCarrier", "DeviceUdiCarrier"],
  ],
  DeviceUdiCarrier: [
    ["carrierAIDC", "base64Binary"],
    ["carrierHRF", "string"],
    ["deviceIdentifier", "string"],
    ["modifierExtension", "Extension"],
  ],
  DeviceDefinition: [
    ["parentDevice", "Reference"],
    ["safety", "CodeableConcept"],
  ],
  DeviceMetric: [
    ["calibration", "DeviceMetricCalibration"],
    ["category", "code"],
    ["color", "code"],
    ["identifier", "Identifier"],
    ["measurementPeriod", "Timing"],
    ["operationalStatus", "code"],
    ["parent", "Reference"],
    ["source", "Reference"],
    ["type", "CodeableConcept"],
    ["unit", "CodeableConcept"],
  ],
  DeviceMetricCalibration: [
    ["modifierExtension", "Extension"],
    ["state", "code"],
    ["time", "instant"],
    ["type", "code"],
  ],
  DeviceRequest: [
    ["authoredOn", "dateTime"],
    ["basedOn", "Reference"],
    ["codeReference", "Reference"],
    ["codeCodeableConcept", "CodeableConcept"],
    ["encounter", "Reference"],
    ["groupIdentifier", "Identifier"],
    ["identifier", "Identifier"],
    ["instantiatesCanonical", "canonical"],
    ["instantiatesUri", "uri"],
    ["intent", "code"],
    ["occurrenceDateTime", "dateTime"],
    ["occurrencePeriod", "Period"],
    ["occurrenceTiming", "Timing"],
    ["performer", "Reference"],
    ["performerType", "CodeableConcept"],
    ["priority", "code"],
    ["priorRequest", "Reference"],
    ["reasonCode", "CodeableConcept"],
    ["reasonReference", "Reference"],
    ["requester", "Reference"],
    ["status", "code"],
    ["subject", "Reference"],
  ],
  DeviceUseStatement: [
    ["basedOn", "Reference"],
    ["bodySite", "CodeableConcept"],
    ["derivedFrom", "Reference"],
    ["device", "Reference"],
    ["identifier", "Identifier"],
    ["reasonCode", "CodeableConcept"],
    ["reasonReference", "Reference"],
    ["recordedOn", "dateTime"],
    ["source", "Reference"],
    ["status", "code"],
    ["subject", "Reference"],
    ["timingTiming", "Timing"],
    ["timingPeriod", "Period"],
    ["timingDateTime", "dateTime"],
  ],
  DiagnosticReport: [
    ["category", "CodeableConcept"],
    ["code", "CodeableConcept"],
    ["effectiveDateTime", "dateTime"],
    ["effectivePeriod", "Period"],
    ["encounter", "Reference"],
    ["identifier", "Identifier"],
    ["issued", "instant"],
    ["media", "DiagnosticReportMedia"],
    ["performer", "Reference"],
    ["resultsInterpreter", "Reference"],
    ["status", "code"],
    ["subject", "Reference"],
  ],
  DiagnosticReportMedia: [
    ["link", "Reference"],
    ["modifierExtension", "Extension"],
  ],
  DocumentManifest: [
    ["author", "Reference"],
    ["content", "Reference"],
    ["description", "string"],
    ["identifier", "Identifier"],
    ["masterIdentifier", "Identifier"],
    ["status", "code"],
    ["subject", "Reference"],
    ["type", "CodeableConcept"],
  ],
  DocumentReference: [
    ["author", "Reference"],
    ["category", "CodeableConcept"],
    ["content", "DocumentReferenceContent"],
    ["context", "DocumentReferenceContext"],
    ["date", "instant"],
    ["description", "string"],
    ["docStatus", "code"],
    ["identifier", "Identifier"],
    ["masterIdentifier", "Identifier"],
    ["relatesTo", "DocumentReferenceRelatesTo"],
    ["securityLabel", "CodeableConcept"],
    ["status", "code"],
    ["subject", "Reference"],
    ["type", "CodeableConcept"],
  ],
  DocumentReferenceContent: [
    ["attachment", "Attachment"],
    ["format", "Coding"],
    ["modifierExtension", "Extension"],
  ],
  DocumentReferenceContext: [
    ["modifierExtension", "Extension"],
    ["period", "Period"],
  ],
  DocumentReferenceRelatesTo: [
    ["code", "code"],
    ["modifierExtension", "Extension"],
    ["target", "Reference"],
  ],
  Encounter: [
    ["appointment", "Reference"],
    ["class", "Coding"],
    ["diagnosis", "EncounterDiagnosis"],
    ["episodeOfCare", "Reference"],
    ["identifier", "Identifier"],
    ["participant", "EncounterParticipant"],
    ["reasonCode", "CodeableConcept"],
    ["reasonReference", "Reference"],
    ["serviceType", "CodeableConcept"],
    ["status", "code"],
    ["subject", "Reference"],
    ["type", "CodeableConcept"],
  ],
  EncounterDiagnosis: [
    ["condition", "Reference"],
    ["modifierExtension", "Extension"],
  ],
  EncounterParticipant: [
    ["individual", "Reference"],
    ["modifierExtension", "Extension"],
    ["type", "CodeableConcept"],
  ],
  Endpoint: [
    ["address", "url"],
    ["connectionType", "Coding"],
    ["identifier", "Identifier"],
    ["managingOrganization", "Reference"],
    ["name", "string"],
    ["payloadMimeType", "code"],
    ["payloadType", "CodeableConcept"],
    ["period", "Period"],
    ["status", "code"],
  ],
  EnrollmentRequest: [["status", "code"]],
  EnrollmentResponse: [["status", "code"]],
  EpisodeOfCare: [
    ["diagnosis", "EpisodeOfCareDiagnosis"],
    ["managingOrganization", "Reference"],
    ["patient", "Reference"],
    ["period", "Period"],
    ["status", "code"],
    ["type", "CodeableConcept"],
  ],
  EpisodeOfCareDiagnosis: [
    ["condition", "Reference"],
    ["modifierExtension", "Extension"],
    ["rank", "positiveInt"],
    ["role", "CodeableConcept"],
  ],
  EventDefinition: [
    ["approvalDate", "date"],
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["effectivePeriod", "Period"],
    ["experimental", "boolean"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["lastReviewDate", "date"],
    ["name", "string"],
    ["publisher", "string"],
    ["status", "code"],
    ["title", "string"],
    ["trigger", "TriggerDefinition"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  Evidence: [
    ["author", "ContactDetail"],
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["endorser", "ContactDetail"],
    ["identifier", "Identifier"],
    ["publisher", "string"],
    ["status", "code"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  EvidenceReport: [
    ["author", "ContactDetail"],
    ["contact", "ContactDetail"],
    ["endorser", "ContactDetail"],
    ["identifier", "Identifier"],
    ["publisher", "string"],
    ["relatedIdentifier", "Identifier"],
    ["status", "code"],
    ["subject", "EvidenceReportSubject"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
  ],
  EvidenceReportSubject: [["modifierExtension", "Extension"]],
  EvidenceVariable: [
    ["characteristic", "EvidenceVariableCharacteristic"],
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["description", "markdown"],
    ["handling", "code"],
    ["identifier", "Identifier"],
    ["name", "string"],
    ["publisher", "string"],
    ["shortTitle", "string"],
    ["status", "code"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  EvidenceVariableCharacteristic: [
    ["definitionReference", "Reference"],
    ["definitionCanonical", "canonical"],
    ["definitionCodeableConcept", "CodeableConcept"],
    ["definitionExpression", "Expression"],
    ["modifierExtension", "Extension"],
  ],
  ExampleScenario: [
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["experimental", "boolean"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["publisher", "string"],
    ["status", "code"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  ExplanationOfBenefit: [
    ["billablePeriod", "Period"],
    ["created", "dateTime"],
    ["insurance", "ExplanationOfBenefitInsurance"],
    ["insurer", "Reference"],
    ["outcome", "code"],
    ["patient", "Reference"],
    ["provider", "Reference"],
    ["status", "code"],
    ["total", "ExplanationOfBenefitTotal"],
    ["type", "CodeableConcept"],
    ["use", "code"],
  ],
  ExplanationOfBenefitInsurance: [
    ["coverage", "Reference"],
    ["focal", "boolean"],
    ["modifierExtension", "Extension"],
  ],
  ExplanationOfBenefitTotal: [
    ["amount", "Money"],
    ["category", "CodeableConcept"],
    ["modifierExtension", "Extension"],
  ],
  FamilyMemberHistory: [
    ["ageAge", "Age"],
    ["ageRange", "Range"],
    ["ageString", "string"],
    ["dataAbsentReason", "CodeableConcept"],
    ["date", "dateTime"],
    ["deceasedBoolean", "boolean"],
    ["deceasedAge", "Age"],
    ["deceasedRange", "Range"],
    ["deceasedDate", "date"],
    ["deceasedString", "string"],
    ["estimatedAge", "boolean"],
    ["identifier", "Identifier"],
    ["instantiatesCanonical", "canonical"],
    ["instantiatesUri", "uri"],
    ["name", "string"],
    ["patient", "Reference"],
    ["reasonCode", "CodeableConcept"],
    ["reasonReference", "Reference"],
    ["relationship", "CodeableConcept"],
    ["sex", "CodeableConcept"],
    ["status", "code"],
  ],
  Flag: [
    ["author", "Reference"],
    ["category", "CodeableConcept"],
    ["code", "CodeableConcept"],
    ["encounter", "Reference"],
    ["identifier", "Identifier"],
    ["period", "Period"],
    ["status", "code"],
    ["subject", "Reference"],
  ],
  Goal: [
    ["achievementStatus", "CodeableConcept"],
    ["category", "CodeableConcept"],
    ["description", "CodeableConcept"],
    ["expressedBy", "Reference"],
    ["lifecycleStatus", "code"],
    ["priority", "CodeableConcept"],
    ["startDate", "date"],
    ["startCodeableConcept", "CodeableConcept"],
    ["statusDate", "date"],
    ["subject", "Reference"],
  ],
  GraphDefinition: [
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["experimental", "boolean"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["publisher", "string"],
    ["start", "code"],
    ["status", "code"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  Group: [
    ["active", "boolean"],
    ["actual", "boolean"],
    ["code", "CodeableConcept"],
    ["identifier", "Identifier"],
    ["managingEntity", "Reference"],
    ["name", "string"],
    ["quantity", "unsignedInt"],
    ["type", "code"],
  ],
  GuidanceResponse: [
    ["identifier", "Identifier"],
    ["moduleUri", "uri"],
    ["moduleCanonical", "canonical"],
    ["moduleCodeableConcept", "CodeableConcept"],
    ["requestIdentifier", "Identifier"],
    ["status", "code"],
  ],
  HealthcareService: [
    ["active", "boolean"],
    ["category", "CodeableConcept"],
    ["comment", "string"],
    ["identifier", "Identifier"],
    ["location", "Reference"],
    ["name", "string"],
    ["photo", "Attachment"],
    ["providedBy", "Reference"],
    ["specialty", "CodeableConcept"],
    ["type", "CodeableConcept"],
  ],
  ImagingStudy: [
    ["basedOn", "Reference"],
    ["description", "string"],
    ["encounter", "Reference"],
    ["endpoint", "Reference"],
    ["identifier", "Identifier"],
    ["interpreter", "Reference"],
    ["location", "Reference"],
    ["modality", "Coding"],
    ["note", "Annotation"],
    ["numberOfInstances", "unsignedInt"],
    ["numberOfSeries", "unsignedInt"],
    ["procedureCode", "CodeableConcept"],
    ["procedureReference", "Reference"],
    ["reasonCode", "CodeableConcept"],
    ["reasonReference", "Reference"],
    ["referrer", "Reference"],
    ["series", "ImagingStudySeries"],
    ["started", "dateTime"],
    ["status", "code"],
    ["subject", "Reference"],
  ],
  ImagingStudySeries: [
    ["bodySite", "Coding"],
    ["description", "string"],
    ["endpoint", "Reference"],
    ["laterality", "Coding"],
    ["modality", "Coding"],
    ["modifierExtension", "Extension"],
    ["number", "unsignedInt"],
    ["numberOfInstances", "unsignedInt"],
    ["performer", "ImagingStudySeriesPerformer"],
    ["specimen", "Reference"],
    ["started", "dateTime"],
    ["uid", "id"],
  ],
  ImagingStudySeriesPerformer: [
    ["actor", "Reference"],
    ["function", "CodeableConcept"],
    ["modifierExtension", "Extension"],
  ],
  Immunization: [
    ["isSubpotent", "boolean"],
    ["note", "Annotation"],
    ["occurrenceDateTime", "dateTime"],
    ["occurrenceString", "string"],
    ["patient", "Reference"],
    ["performer", "ImmunizationPerformer"],
    ["primarySource", "boolean"],
    ["status", "code"],
    ["vaccineCode", "CodeableConcept"],
  ],
  ImmunizationPerformer: [
    ["actor", "Reference"],
    ["function", "CodeableConcept"],
    ["modifierExtension", "Extension"],
  ],
  ImmunizationEvaluation: [
    ["doseStatus", "CodeableConcept"],
    ["immunizationEvent", "Reference"],
    ["patient", "Reference"],
    ["status", "code"],
    ["targetDisease", "CodeableConcept"],
  ],
  ImmunizationRecommendation: [
    ["date", "dateTime"],
    ["identifier", "Identifier"],
    ["patient", "Reference"],
    ["recommendation", "ImmunizationRecommendationRecommendation"],
  ],
  ImmunizationRecommendationRecommendation: [
    ["contraindicatedVaccineCode", "CodeableConcept"],
    ["doseNumberPositiveInt", "positiveInt"],
    ["doseNumberString", "string"],
    ["forecastReason", "CodeableConcept"],
    ["forecastStatus", "CodeableConcept"],
    ["modifierExtension", "Extension"],
    ["targetDisease", "CodeableConcept"],
    ["vaccineCode", "CodeableConcept"],
  ],
  ImplementationGuide: [
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["dependsOn", "ImplementationGuideDependsOn"],
    ["experimental", "boolean"],
    ["fhirVersion", "code"],
    ["global", "ImplementationGuideGlobal"],
    ["jurisdiction", "CodeableConcept"],
    ["license", "code"],
    ["name", "string"],
    ["packageId", "id"],
    ["publisher", "string"],
    ["status", "code"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  ImplementationGuideDependsOn: [
    ["modifierExtension", "Extension"],
    ["packageId", "id"],
    ["uri", "canonical"],
    ["version", "string"],
  ],
  ImplementationGuideGlobal: [
    ["modifierExtension", "Extension"],
    ["profile", "canonical"],
    ["type", "code"],
  ],
  ImplementationGuideManifestResource: [
    ["modifierExtension", "Extension"],
    ["reference", "Reference"],
  ],
  Ingredient: [
    ["allergenicIndicator", "boolean"],
    ["for", "Reference"],
    ["function", "CodeableConcept"],
    ["identifier", "Identifier"],
    ["manufacturer", "IngredientManufacturer"],
    ["role", "CodeableConcept"],
    ["status", "code"],
    ["substance", "IngredientSubstance"],
  ],
  IngredientManufacturer: [
    ["manufacturer", "Reference"],
    ["modifierExtension", "Extension"],
    ["role", "code"],
  ],
  IngredientSubstance: [
    ["code", "CodeableReference"],
    ["modifierExtension", "Extension"],
    ["strength", "IngredientSubstanceStrength"],
  ],
  IngredientSubstanceStrength: [
    ["concentrationRatio", "Ratio"],
    ["concentrationRatioRange", "RatioRange"],
    ["country", "CodeableConcept"],
    ["measurementPoint", "string"],
    ["modifierExtension", "Extension"],
    ["presentationRatio", "Ratio"],
    ["presentationRatioRange", "RatioRange"],
    ["referenceStrength", "IngredientSubstanceStrengthReferenceStrength"],
    ["textConcentration", "string"],
    ["textPresentation", "string"],
  ],
  IngredientSubstanceStrengthReferenceStrength: [
    ["country", "CodeableConcept"],
    ["measurementPoint", "string"],
    ["modifierExtension", "Extension"],
    ["strengthRatio", "Ratio"],
    ["strengthRatioRange", "RatioRange"],
    ["substance", "CodeableReference"],
  ],
  InsurancePlan: [
    ["administeredBy", "Reference"],
    ["coverageArea", "Reference"],
    ["identifier", "Identifier"],
    ["name", "string"],
    ["ownedBy", "Reference"],
    ["status", "code"],
    ["type", "CodeableConcept"],
  ],
  Invoice: [
    ["date", "dateTime"],
    ["identifier", "Identifier"],
    ["recipient", "Reference"],
    ["status", "code"],
    ["subject", "Reference"],
    ["totalGross", "Money"],
    ["totalNet", "Money"],
    ["type", "CodeableConcept"],
  ],
  Library: [
    ["contact", "ContactDetail"],
    ["content", "Attachment"],
    ["date", "dateTime"],
    ["description", "markdown"],
    ["effectivePeriod", "Period"],
    ["experimental", "boolean"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["publisher", "string"],
    ["status", "code"],
    ["title", "string"],
    ["type", "CodeableConcept"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  Linkage: [
    ["active", "boolean"],
    ["author", "Reference"],
    ["item", "LinkageItem"],
  ],
  LinkageItem: [
    ["modifierExtension", "Extension"],
    ["resource", "Reference"],
    ["type", "code"],
  ],
  List: [
    ["code", "CodeableConcept"],
    ["date", "dateTime"],
    ["mode", "code"],
    ["source", "Reference"],
    ["status", "code"],
    ["subject", "Reference"],
    ["title", "string"],
  ],
  Location: [
    ["description", "string"],
    ["identifier", "Identifier"],
    ["managingOrganization", "Reference"],
    ["mode", "code"],
    ["name", "string"],
    ["operationalStatus", "Coding"],
    ["physicalType", "CodeableConcept"],
    ["status", "code"],
    ["type", "CodeableConcept"],
  ],
  ManufacturedItemDefinition: [
    ["identifier", "Identifier"],
    ["ingredient", "CodeableConcept"],
    ["manufacturedDoseForm", "CodeableConcept"],
    ["manufacturer", "Reference"],
    ["property", "ManufacturedItemDefinitionProperty"],
    ["status", "code"],
    ["unitOfPresentation", "CodeableConcept"],
  ],
  ManufacturedItemDefinitionProperty: [
    ["modifierExtension", "Extension"],
    ["type", "CodeableConcept"],
    ["valueCodeableConcept", "CodeableConcept"],
    ["valueQuantity", "Quantity"],
    ["valueDate", "date"],
    ["valueBoolean", "boolean"],
    ["valueAttachment", "Attachment"],
  ],
  Measure: [
    ["clinicalRecommendationStatement", "markdown"],
    ["compositeScoring", "CodeableConcept"],
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["definition", "markdown"],
    ["description", "markdown"],
    ["disclaimer", "markdown"],
    ["effectivePeriod", "Period"],
    ["experimental", "boolean"],
    ["guidance", "markdown"],
    ["identifier", "Identifier"],
    ["improvementNotation", "CodeableConcept"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["publisher", "string"],
    ["rateAggregation", "string"],
    ["rationale", "markdown"],
    ["riskAdjustment", "string"],
    ["scoring", "CodeableConcept"],
    ["status", "code"],
    ["title", "string"],
    ["type", "CodeableConcept"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  MeasureReport: [
    ["date", "dateTime"],
    ["identifier", "Identifier"],
    ["improvementNotation", "CodeableConcept"],
    ["measure", "canonical"],
    ["period", "Period"],
    ["reporter", "Reference"],
    ["status", "code"],
    ["subject", "Reference"],
    ["type", "code"],
  ],
  Media: [
    ["basedOn", "Reference"],
    ["bodySite", "CodeableConcept"],
    ["content", "Attachment"],
    ["createdDateTime", "dateTime"],
    ["createdPeriod", "Period"],
    ["device", "Reference"],
    ["deviceName", "string"],
    ["duration", "decimal"],
    ["encounter", "Reference"],
    ["frames", "positiveInt"],
    ["height", "positiveInt"],
    ["identifier", "Identifier"],
    ["issued", "instant"],
    ["modality", "CodeableConcept"],
    ["operator", "Reference"],
    ["partOf", "Reference"],
    ["reasonCode", "CodeableConcept"],
    ["status", "code"],
    ["subject", "Reference"],
    ["type", "CodeableConcept"],
    ["view", "CodeableConcept"],
    ["width", "positiveInt"],
  ],
  Medication: [
    ["amount", "Ratio"],
    ["code", "CodeableConcept"],
    ["identifier", "Identifier"],
    ["manufacturer", "Reference"],
    ["status", "code"],
  ],
  MedicationAdministration: [
    ["effectiveDateTime", "dateTime"],
    ["effectivePeriod", "Period"],
    ["instantiates", "uri"],
    ["medicationCodeableConcept", "CodeableConcept"],
    ["medicationReference", "Reference"],
    ["partOf", "Reference"],
    ["performer", "MedicationAdministrationPerformer"],
    ["status", "code"],
    ["subject", "Reference"],
  ],
  MedicationAdministrationPerformer: [
    ["actor", "Reference"],
    ["modifierExtension", "Extension"],
  ],
  MedicationDispense: [
    ["medicationCodeableConcept", "CodeableConcept"],
    ["medicationReference", "Reference"],
    ["status", "code"],
    ["subject", "Reference"],
    ["whenPrepared", "dateTime"],
  ],
  MedicationKnowledge: [
    ["amount", "Quantity"],
    ["code", "CodeableConcept"],
    ["manufacturer", "Reference"],
    ["status", "code"],
    ["synonym", "string"],
  ],
  MedicationRequest: [
    ["authoredOn", "dateTime"],
    ["basedOn", "Reference"],
    ["doNotPerform", "boolean"],
    ["groupIdentifier", "Identifier"],
    ["instantiatesCanonical", "canonical"],
    ["instantiatesUri", "uri"],
    ["intent", "code"],
    ["medicationCodeableConcept", "CodeableConcept"],
    ["medicationReference", "Reference"],
    ["performerType", "CodeableConcept"],
    ["priority", "code"],
    ["reportedBoolean", "boolean"],
    ["reportedReference", "Reference"],
    ["requester", "Reference"],
    ["status", "code"],
    ["subject", "Reference"],
  ],
  MedicationStatement: [
    ["basedOn", "Reference"],
    ["category", "CodeableConcept"],
    ["context", "Reference"],
    ["dateAsserted", "dateTime"],
    ["effectiveDateTime", "dateTime"],
    ["effectivePeriod", "Period"],
    ["identifier", "Identifier"],
    ["medicationCodeableConcept", "CodeableConcept"],
    ["medicationReference", "Reference"],
    ["partOf", "Reference"],
    ["status", "code"],
    ["subject", "Reference"],
  ],
  MedicinalProductDefinition: [
    ["additionalMonitoringIndicator", "CodeableConcept"],
    ["attachedDocument", "Reference"],
    ["characteristic", "MedicinalProductDefinitionCharacteristic"],
    ["classification", "CodeableConcept"],
    ["clinicalTrial", "Reference"],
    ["code", "Coding"],
    ["combinedPharmaceuticalDoseForm", "CodeableConcept"],
    ["contact", "MedicinalProductDefinitionContact"],
    ["crossReference", "MedicinalProductDefinitionCrossReference"],
    ["description", "markdown"],
    ["domain", "CodeableConcept"],
    ["identifier", "Identifier"],
    ["impurity", "CodeableReference"],
    ["indication", "markdown"],
    ["ingredient", "CodeableConcept"],
    ["legalStatusOfSupply", "CodeableConcept"],
    ["marketingStatus", "MarketingStatus"],
    ["masterFile", "Reference"],
    ["name", "MedicinalProductDefinitionName"],
    ["operation", "MedicinalProductDefinitionOperation"],
    ["packagedMedicinalProduct", "CodeableConcept"],
    ["pediatricUseIndicator", "CodeableConcept"],
    ["route", "CodeableConcept"],
    ["specialMeasures", "CodeableConcept"],
    ["status", "CodeableConcept"],
    ["statusDate", "dateTime"],
    ["type", "CodeableConcept"],
    ["version", "string"],
  ],
  MedicinalProductDefinitionCharacteristic: [
    ["modifierExtension", "Extension"],
    ["type", "CodeableConcept"],
    ["valueCodeableConcept", "CodeableConcept"],
    ["valueQuantity", "Quantity"],
    ["valueDate", "date"],
    ["valueBoolean", "boolean"],
    ["valueAttachment", "Attachment"],
  ],
  MedicinalProductDefinitionContact: [
    ["contact", "Reference"],
    ["modifierExtension", "Extension"],
    ["type", "CodeableConcept"],
  ],
  MedicinalProductDefinitionCrossReference: [
    ["modifierExtension", "Extension"],
    ["product", "CodeableReference"],
    ["type", "CodeableConcept"],
  ],
  MedicinalProductDefinitionName: [
    ["countryLanguage", "MedicinalProductDefinitionNameCountryLanguage"],
    ["modifierExtension", "Extension"],
    ["namePart", "MedicinalProductDefinitionNameNamePart"],
    ["productName", "string"],
    ["type", "CodeableConcept"],
  ],
  MedicinalProductDefinitionNameCountryLanguage: [
    ["country", "CodeableConcept"],
    ["jurisdiction", "CodeableConcept"],
    ["language", "CodeableConcept"],
    ["modifierExtension", "Extension"],
  ],
  MedicinalProductDefinitionNameNamePart: [
    ["modifierExtension", "Extension"],
    ["part", "string"],
    ["type", "CodeableConcept"],
  ],
  MedicinalProductDefinitionOperation: [
    ["confidentialityIndicator", "CodeableConcept"],
    ["effectiveDate", "Period"],
    ["modifierExtension", "Extension"],
    ["organization", "Reference"],
    ["type", "CodeableReference"],
  ],
  MessageDefinition: [
    ["base", "canonical"],
    ["category", "code"],
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["description", "markdown"],
    ["eventCoding", "Coding"],
    ["eventUri", "uri"],
    ["experimental", "boolean"],
    ["focus", "MessageDefinitionFocus"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["parent", "canonical"],
    ["publisher", "string"],
    ["purpose", "markdown"],
    ["replaces", "canonical"],
    ["status", "code"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  MessageDefinitionFocus: [
    ["code", "code"],
    ["min", "unsignedInt"],
    ["modifierExtension", "Extension"],
  ],
  MessageHeader: [
    ["author", "Reference"],
    ["definition", "canonical"],
    ["destination", "MessageHeaderDestination"],
    ["enterer", "Reference"],
    ["eventCoding", "Coding"],
    ["eventUri", "uri"],
    ["focus", "Reference"],
    ["reason", "CodeableConcept"],
    ["response", "MessageHeaderResponse"],
    ["responsible", "Reference"],
    ["sender", "Reference"],
    ["source", "MessageHeaderSource"],
  ],
  MessageHeaderDestination: [
    ["endpoint", "url"],
    ["modifierExtension", "Extension"],
    ["name", "string"],
    ["receiver", "Reference"],
    ["target", "Reference"],
  ],
  MessageHeaderResponse: [
    ["code", "code"],
    ["details", "Reference"],
    ["identifier", "id"],
    ["modifierExtension", "Extension"],
  ],
  MessageHeaderSource: [
    ["contact", "ContactPoint"],
    ["endpoint", "url"],
    ["modifierExtension", "Extension"],
    ["name", "string"],
    ["software", "string"],
    ["version", "string"],
  ],
  MolecularSequence: [
    ["coordinateSystem", "integer"],
    ["device", "Reference"],
    ["identifier", "Identifier"],
    ["observedSeq", "string"],
    ["patient", "Reference"],
    ["performer", "Reference"],
    ["pointer", "Reference"],
    ["quality", "MolecularSequenceQuality"],
    ["quantity", "Quantity"],
    ["readCoverage", "integer"],
    ["referenceSeq", "MolecularSequenceReferenceSeq"],
    ["repository", "MolecularSequenceRepository"],
    ["specimen", "Reference"],
    ["structureVariant", "MolecularSequenceStructureVariant"],
    ["type", "code"],
    ["variant", "MolecularSequenceVariant"],
  ],
  MolecularSequenceQuality: [
    ["end", "integer"],
    ["fScore", "decimal"],
    ["gtFP", "decimal"],
    ["method", "CodeableConcept"],
    ["modifierExtension", "Extension"],
    ["precision", "decimal"],
    ["queryFP", "decimal"],
    ["queryTP", "decimal"],
    ["recall", "decimal"],
    ["roc", "MolecularSequenceQualityRoc"],
    ["score", "Quantity"],
    ["standardSequence", "CodeableConcept"],
    ["start", "integer"],
    ["truthFN", "decimal"],
    ["truthTP", "decimal"],
    ["type", "code"],
  ],
  MolecularSequenceQualityRoc: [
    ["fMeasure", "decimal"],
    ["modifierExtension", "Extension"],
    ["numFN", "integer"],
    ["numFP", "integer"],
    ["numTP", "integer"],
    ["precision", "decimal"],
    ["score", "integer"],
    ["sensitivity", "decimal"],
  ],
  MolecularSequenceReferenceSeq: [
    ["chromosome", "CodeableConcept"],
    ["genomeBuild", "string"],
    ["modifierExtension", "Extension"],
    ["orientation", "code"],
    ["referenceSeqId", "CodeableConcept"],
    ["referenceSeqPointer", "Reference"],
    ["referenceSeqString", "string"],
    ["strand", "code"],
    ["windowEnd", "integer"],
    ["windowStart", "integer"],
  ],
  MolecularSequenceRepository: [
    ["datasetId", "string"],
    ["modifierExtension", "Extension"],
    ["name", "string"],
    ["readsetId", "string"],
    ["type", "code"],
    ["url", "uri"],
    ["variantsetId", "string"],
  ],
  MolecularSequenceStructureVariant: [
    ["exact", "boolean"],
    ["inner", "MolecularSequenceStructureVariantInner"],
    ["length", "integer"],
    ["modifierExtension", "Extension"],
    ["outer", "MolecularSequenceStructureVariantOuter"],
    ["variantType", "CodeableConcept"],
  ],
  MolecularSequenceStructureVariantInner: [
    ["end", "integer"],
    ["modifierExtension", "Extension"],
    ["start", "integer"],
  ],
  MolecularSequenceStructureVariantOuter: [
    ["end", "integer"],
    ["modifierExtension", "Extension"],
    ["start", "integer"],
  ],
  MolecularSequenceVariant: [
    ["cigar", "string"],
    ["end", "integer"],
    ["modifierExtension", "Extension"],
    ["observedAllele", "string"],
    ["referenceAllele", "string"],
    ["start", "integer"],
    ["variantPointer", "Reference"],
  ],
  NamingSystem: [
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["jurisdiction", "CodeableConcept"],
    ["kind", "code"],
    ["name", "string"],
    ["publisher", "string"],
    ["status", "code"],
    ["uniqueId", "NamingSystemUniqueId"],
    ["useContext", "UsageContext"],
  ],
  NamingSystemUniqueId: [
    ["modifierExtension", "Extension"],
    ["type", "code"],
    ["value", "string"],
  ],
  NutritionOrder: [
    ["dateTime", "dateTime"],
    ["instantiatesCanonical", "canonical"],
    ["instantiatesUri", "uri"],
    ["intent", "code"],
    ["orderer", "Reference"],
    ["patient", "Reference"],
    ["status", "code"],
  ],
  NutritionProduct: [
    ["category", "CodeableConcept"],
    ["code", "CodeableConcept"],
    ["manufacturer", "Reference"],
    ["nutrient", "NutritionProductNutrient"],
    ["status", "code"],
  ],
  NutritionProductNutrient: [["modifierExtension", "Extension"]],
  Observation: [
    ["basedOn", "Reference"],
    ["code", "CodeableConcept"],
    ["component", "ObservationComponent"],
    ["derivedFrom", "Reference"],
    ["effectiveDateTime", "dateTime"],
    ["effectivePeriod", "Period"],
    ["effectiveTiming", "Timing"],
    ["effectiveInstant", "instant"],
    ["encounter", "Reference"],
    ["focus", "Reference"],
    ["hasMember", "Reference"],
    ["identifier", "Identifier"],
    ["issued", "instant"],
    ["partOf", "Reference"],
    ["performer", "Reference"],
    ["status", "code"],
    ["subject", "Reference"],
    ["valueQuantity", "Quantity"],
    ["valueCodeableConcept", "CodeableConcept"],
    ["valueString", "string"],
    ["valueBoolean", "boolean"],
    ["valueInteger", "integer"],
    ["valueRange", "Range"],
    ["valueRatio", "Ratio"],
    ["valueSampledData", "SampledData"],
    ["valueTime", "time"],
    ["valueDateTime", "dateTime"],
    ["valuePeriod", "Period"],
  ],
  ObservationComponent: [
    ["code", "CodeableConcept"],
    ["modifierExtension", "Extension"],
    ["valueQuantity", "Quantity"],
    ["valueCodeableConcept", "CodeableConcept"],
    ["valueString", "string"],
    ["valueBoolean", "boolean"],
    ["valueInteger", "integer"],
    ["valueRange", "Range"],
    ["valueRatio", "Ratio"],
    ["valueSampledData", "SampledData"],
    ["valueTime", "time"],
    ["valueDateTime", "dateTime"],
    ["valuePeriod", "Period"],
  ],
  ObservationDefinition: [
    ["category", "CodeableConcept"],
    ["code", "CodeableConcept"],
    ["identifier", "Identifier"],
  ],
  OperationDefinition: [
    ["affectsState", "boolean"],
    ["base", "canonical"],
    ["code", "code"],
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["experimental", "boolean"],
    ["instance", "boolean"],
    ["jurisdiction", "CodeableConcept"],
    ["kind", "code"],
    ["name", "string"],
    ["publisher", "string"],
    ["resource", "code"],
    ["status", "code"],
    ["system", "boolean"],
    ["title", "string"],
    ["type", "boolean"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  OperationOutcome: [["issue", "OperationOutcomeIssue"]],
  OperationOutcomeIssue: [
    ["code", "code"],
    ["details", "CodeableConcept"],
    ["diagnostics", "string"],
    ["expression", "string"],
    ["location", "string"],
    ["modifierExtension", "Extension"],
    ["severity", "code"],
  ],
  Organization: [
    ["active", "boolean"],
    ["identifier", "Identifier"],
    ["name", "string"],
    ["partOf", "Reference"],
    ["type", "CodeableConcept"],
  ],
  OrganizationAffiliation: [
    ["active", "boolean"],
    ["code", "CodeableConcept"],
    ["identifier", "Identifier"],
    ["location", "Reference"],
    ["network", "Reference"],
    ["organization", "Reference"],
    ["participatingOrganization", "Reference"],
    ["period", "Period"],
    ["specialty", "CodeableConcept"],
    ["telecom", "ContactPoint"],
  ],
  PackagedProductDefinition: [
    ["characteristic", "CodeableConcept"],
    ["containedItemQuantity", "Quantity"],
    ["copackagedIndicator", "boolean"],
    ["description", "markdown"],
    ["identifier", "Identifier"],
    ["legalStatusOfSupply", "PackagedProductDefinitionLegalStatusOfSupply"],
    ["manufacturer", "Reference"],
    ["marketingStatus", "MarketingStatus"],
    ["name", "string"],
    ["package", "PackagedProductDefinitionPackage"],
    ["packageFor", "Reference"],
    ["status", "CodeableConcept"],
    ["statusDate", "dateTime"],
    ["type", "CodeableConcept"],
  ],
  PackagedProductDefinitionLegalStatusOfSupply: [
    ["code", "CodeableConcept"],
    ["jurisdiction", "CodeableConcept"],
    ["modifierExtension", "Extension"],
  ],
  PackagedProductDefinitionPackage: [
    ["alternateMaterial", "CodeableConcept"],
    ["containedItem", "PackagedProductDefinitionPackageContainedItem"],
    ["identifier", "Identifier"],
    ["manufacturer", "Reference"],
    ["material", "CodeableConcept"],
    ["modifierExtension", "Extension"],
    ["property", "PackagedProductDefinitionPackageProperty"],
    ["quantity", "integer"],
    ["shelfLifeStorage", "PackagedProductDefinitionPackageShelfLifeStorage"],
    ["type", "CodeableConcept"],
  ],
  PackagedProductDefinitionPackageContainedItem: [
    ["amount", "Quantity"],
    ["item", "CodeableReference"],
    ["modifierExtension", "Extension"],
  ],
  PackagedProductDefinitionPackageProperty: [
    ["modifierExtension", "Extension"],
    ["type", "CodeableConcept"],
    ["valueCodeableConcept", "CodeableConcept"],
    ["valueQuantity", "Quantity"],
    ["valueDate", "date"],
    ["valueBoolean", "boolean"],
    ["valueAttachment", "Attachment"],
  ],
  PackagedProductDefinitionPackageShelfLifeStorage: [
    ["modifierExtension", "Extension"],
    ["periodDuration", "Duration"],
    ["periodString", "string"],
    ["specialPrecautionsForStorage", "CodeableConcept"],
    ["type", "CodeableConcept"],
  ],
  Patient: [
    ["active", "boolean"],
    ["address", "Address"],
    ["birthDate", "date"],
    ["deceasedBoolean", "boolean"],
    ["deceasedDateTime", "dateTime"],
    ["gender", "code"],
    ["identifier", "Identifier"],
    ["link", "PatientLink"],
    ["managingOrganization", "Reference"],
    ["name", "HumanName"],
    ["telecom", "ContactPoint"],
  ],
  PatientLink: [
    ["modifierExtension", "Extension"],
    ["other", "Reference"],
    ["type", "code"],
  ],
  PaymentNotice: [
    ["amount", "Money"],
    ["created", "dateTime"],
    ["payment", "Reference"],
    ["recipient", "Reference"],
    ["status", "code"],
  ],
  PaymentReconciliation: [
    ["created", "dateTime"],
    ["paymentAmount", "Money"],
    ["paymentDate", "date"],
    ["paymentIssuer", "Reference"],
    ["period", "Period"],
    ["status", "code"],
  ],
  Person: [
    ["active", "boolean"],
    ["birthDate", "date"],
    ["gender", "code"],
    ["managingOrganization", "Reference"],
    ["name", "HumanName"],
    ["telecom", "ContactPoint"],
  ],
  PlanDefinition: [
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["description", "markdown"],
    ["effectivePeriod", "Period"],
    ["experimental", "boolean"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["publisher", "string"],
    ["status", "code"],
    ["title", "string"],
    ["type", "CodeableConcept"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  Practitioner: [
    ["active", "boolean"],
    ["address", "Address"],
    ["birthDate", "date"],
    ["gender", "code"],
    ["identifier", "Identifier"],
    ["name", "HumanName"],
    ["telecom", "ContactPoint"],
  ],
  PractitionerRole: [
    ["active", "boolean"],
    ["code", "CodeableConcept"],
    ["identifier", "Identifier"],
    ["location", "Reference"],
    ["organization", "Reference"],
    ["period", "Period"],
    ["practitioner", "Reference"],
    ["specialty", "CodeableConcept"],
    ["telecom", "ContactPoint"],
  ],
  Procedure: [
    ["asserter", "Reference"],
    ["basedOn", "Reference"],
    ["bodySite", "CodeableConcept"],
    ["category", "CodeableConcept"],
    ["code", "CodeableConcept"],
    ["encounter", "Reference"],
    ["identifier", "Identifier"],
    ["instantiatesCanonical", "canonical"],
    ["instantiatesUri", "uri"],
    ["location", "Reference"],
    ["outcome", "CodeableConcept"],
    ["partOf", "Reference"],
    ["performedDateTime", "dateTime"],
    ["performedPeriod", "Period"],
    ["performedString", "string"],
    ["performedAge", "Age"],
    ["performedRange", "Range"],
    ["performer", "ProcedurePerformer"],
    ["reasonCode", "CodeableConcept"],
    ["reasonReference", "Reference"],
    ["recorder", "Reference"],
    ["status", "code"],
    ["statusReason", "CodeableConcept"],
    ["subject", "Reference"],
  ],
  ProcedurePerformer: [
    ["actor", "Reference"],
    ["function", "CodeableConcept"],
    ["modifierExtension", "Extension"],
  ],
  Provenance: [
    ["recorded", "instant"],
    ["target", "Reference"],
  ],
  Questionnaire: [
    ["code", "Coding"],
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["effectivePeriod", "Period"],
    ["experimental", "boolean"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["publisher", "string"],
    ["status", "code"],
    ["subjectType", "code"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  QuestionnaireResponse: [
    ["author", "Reference"],
    ["authored", "dateTime"],
    ["basedOn", "Reference"],
    ["encounter", "Reference"],
    ["identifier", "Identifier"],
    ["partOf", "Reference"],
    ["questionnaire", "canonical"],
    ["source", "Reference"],
    ["status", "code"],
    ["subject", "Reference"],
  ],
  RegulatedAuthorization: [
    ["basis", "CodeableConcept"],
    ["case", "RegulatedAuthorizationCase"],
    ["description", "markdown"],
    ["holder", "Reference"],
    ["identifier", "Identifier"],
    ["indication", "CodeableReference"],
    ["intendedUse", "CodeableConcept"],
    ["region", "CodeableConcept"],
    ["regulator", "Reference"],
    ["status", "CodeableConcept"],
    ["statusDate", "dateTime"],
    ["subject", "Reference"],
    ["type", "CodeableConcept"],
    ["validityPeriod", "Period"],
  ],
  RegulatedAuthorizationCase: [
    ["datePeriod", "Period"],
    ["dateDateTime", "dateTime"],
    ["identifier", "Identifier"],
    ["modifierExtension", "Extension"],
    ["status", "CodeableConcept"],
    ["type", "CodeableConcept"],
  ],
  RelatedPerson: [
    ["active", "boolean"],
    ["address", "Address"],
    ["birthDate", "date"],
    ["gender", "code"],
    ["identifier", "Identifier"],
    ["name", "HumanName"],
    ["patient", "Reference"],
    ["relationship", "CodeableConcept"],
    ["telecom", "ContactPoint"],
  ],
  RequestGroup: [
    ["code", "CodeableConcept"],
    ["groupIdentifier", "Identifier"],
    ["identifier", "Identifier"],
    ["instantiatesCanonical", "canonical"],
    ["instantiatesUri", "uri"],
    ["intent", "code"],
    ["priority", "code"],
    ["status", "code"],
  ],
  ResearchDefinition: [
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["description", "markdown"],
    ["effectivePeriod", "Period"],
    ["experimental", "boolean"],
    ["exposure", "Reference"],
    ["exposureAlternative", "Reference"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["outcome", "Reference"],
    ["population", "Reference"],
    ["publisher", "string"],
    ["status", "code"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  ResearchElementDefinition: [
    ["characteristic", "ResearchElementDefinitionCharacteristic"],
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["description", "markdown"],
    ["effectivePeriod", "Period"],
    ["experimental", "boolean"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["publisher", "string"],
    ["shortTitle", "string"],
    ["status", "code"],
    ["title", "string"],
    ["type", "code"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  ResearchElementDefinitionCharacteristic: [
    ["definitionCodeableConcept", "CodeableConcept"],
    ["definitionCanonical", "canonical"],
    ["definitionExpression", "Expression"],
    ["definitionDataRequirement", "DataRequirement"],
    ["modifierExtension", "Extension"],
  ],
  ResearchStudy: [
    ["category", "CodeableConcept"],
    ["condition", "CodeableConcept"],
    ["contact", "ContactDetail"],
    ["enrollment", "Reference"],
    ["focus", "CodeableConcept"],
    ["identifier", "Identifier"],
    ["keyword", "CodeableConcept"],
    ["location", "CodeableConcept"],
    ["partOf", "Reference"],
    ["period", "Period"],
    ["phase", "CodeableConcept"],
    ["primaryPurposeType", "CodeableConcept"],
    ["principalInvestigator", "Reference"],
    ["protocol", "Reference"],
    ["reasonStopped", "CodeableConcept"],
    ["site", "Reference"],
    ["sponsor", "Reference"],
    ["status", "code"],
    ["title", "string"],
  ],
  ResearchSubject: [
    ["identifier", "Identifier"],
    ["individual", "Reference"],
    ["period", "Period"],
    ["status", "code"],
    ["study", "Reference"],
  ],
  RiskAssessment: [
    ["code", "CodeableConcept"],
    ["condition", "Reference"],
    ["encounter", "Reference"],
    ["identifier", "Identifier"],
    ["method", "CodeableConcept"],
    ["occurrenceDateTime", "dateTime"],
    ["occurrencePeriod", "Period"],
    ["performer", "Reference"],
    ["status", "code"],
    ["subject", "Reference"],
  ],
  Schedule: [
    ["active", "boolean"],
    ["actor", "Reference"],
    ["identifier", "Identifier"],
    ["planningHorizon", "Period"],
    ["serviceCategory", "CodeableConcept"],
    ["serviceType", "CodeableConcept"],
    ["specialty", "CodeableConcept"],
  ],
  SearchParameter: [
    ["base", "code"],
    ["code", "code"],
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["description", "markdown"],
    ["experimental", "boolean"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["publisher", "string"],
    ["status", "code"],
    ["type", "code"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  ServiceRequest: [
    ["asNeededBoolean", "boolean"],
    ["asNeededCodeableConcept", "CodeableConcept"],
    ["authoredOn", "dateTime"],
    ["basedOn", "Reference"],
    ["bodySite", "CodeableConcept"],
    ["category", "CodeableConcept"],
    ["code", "CodeableConcept"],
    ["doNotPerform", "boolean"],
    ["encounter", "Reference"],
    ["identifier", "Identifier"],
    ["instantiatesCanonical", "canonical"],
    ["instantiatesUri", "uri"],
    ["intent", "code"],
    ["locationCode", "CodeableConcept"],
    ["locationReference", "Reference"],
    ["occurrenceDateTime", "dateTime"],
    ["occurrencePeriod", "Period"],
    ["occurrenceTiming", "Timing"],
    ["orderDetail", "CodeableConcept"],
    ["patientInstruction", "string"],
    ["performer", "Reference"],
    ["performerType", "CodeableConcept"],
    ["priority", "code"],
    ["quantityQuantity", "Quantity"],
    ["quantityRatio", "Ratio"],
    ["quantityRange", "Range"],
    ["reasonCode", "CodeableConcept"],
    ["reasonReference", "Reference"],
    ["replaces", "Reference"],
    ["requester", "Reference"],
    ["requisition", "Identifier"],
    ["specimen", "Reference"],
    ["status", "code"],
    ["subject", "Reference"],
  ],
  Slot: [
    ["appointmentType", "CodeableConcept"],
    ["end", "instant"],
    ["identifier", "Identifier"],
    ["schedule", "Reference"],
    ["serviceCategory", "CodeableConcept"],
    ["serviceType", "CodeableConcept"],
    ["specialty", "CodeableConcept"],
    ["start", "instant"],
    ["status", "code"],
  ],
  Specimen: [
    ["accessionIdentifier", "Identifier"],
    ["condition", "CodeableConcept"],
    ["identifier", "Identifier"],
    ["receivedTime", "dateTime"],
    ["status", "code"],
    ["subject", "Reference"],
    ["type", "CodeableConcept"],
  ],
  SpecimenDefinition: [
    ["collection", "CodeableConcept"],
    ["identifier", "Identifier"],
    ["patientPreparation", "CodeableConcept"],
    ["timeAspect", "string"],
    ["typeCollected", "CodeableConcept"],
  ],
  StructureDefinition: [
    ["abstract", "boolean"],
    ["baseDefinition", "canonical"],
    ["contact", "ContactDetail"],
    ["context", "StructureDefinitionContext"],
    ["contextInvariant", "string"],
    ["date", "dateTime"],
    ["derivation", "code"],
    ["experimental", "boolean"],
    ["fhirVersion", "code"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["keyword", "Coding"],
    ["kind", "code"],
    ["name", "string"],
    ["publisher", "string"],
    ["status", "code"],
    ["title", "string"],
    ["type", "uri"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  StructureDefinitionContext: [
    ["expression", "string"],
    ["modifierExtension", "Extension"],
    ["type", "code"],
  ],
  StructureMap: [
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["experimental", "boolean"],
    ["group", "StructureMapGroup"],
    ["identifier", "Identifier"],
    ["import", "canonical"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["publisher", "string"],
    ["status", "code"],
    ["structure", "StructureMapStructure"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  StructureMapGroup: [
    ["documentation", "string"],
    ["extends", "id"],
    ["input", "StructureMapGroupInput"],
    ["modifierExtension", "Extension"],
    ["name", "id"],
    ["rule", "StructureMapGroupRule"],
    ["typeMode", "code"],
  ],
  StructureMapGroupInput: [
    ["mode", "code"],
    ["modifierExtension", "Extension"],
    ["name", "id"],
    ["type", "string"],
  ],
  StructureMapGroupRule: [
    ["dependent", "StructureMapGroupRuleDependent"],
    ["modifierExtension", "Extension"],
    ["name", "id"],
    ["source", "StructureMapGroupRuleSource"],
    ["target", "StructureMapGroupRuleTarget"],
  ],
  StructureMapGroupRuleDependent: [
    ["modifierExtension", "Extension"],
    ["name", "id"],
    ["variable", "string"],
  ],
  StructureMapGroupRuleSource: [
    ["check", "string"],
    ["condition", "string"],
    ["context", "id"],
    ["defaultValueBase64Binary", "base64Binary"],
    ["defaultValueBoolean", "boolean"],
    ["defaultValueCanonical", "canonical"],
    ["defaultValueCode", "code"],
    ["defaultValueDate", "date"],
    ["defaultValueDateTime", "dateTime"],
    ["defaultValueDecimal", "decimal"],
    ["defaultValueId", "id"],
    ["defaultValueInstant", "instant"],
    ["defaultValueInteger", "integer"],
    ["defaultValueMarkdown", "markdown"],
    ["defaultValueOid", "oid"],
    ["defaultValuePositiveInt", "positiveInt"],
    ["defaultValueString", "string"],
    ["defaultValueTime", "time"],
    ["defaultValueUnsignedInt", "unsignedInt"],
    ["defaultValueUri", "uri"],
    ["defaultValueUrl", "url"],
    ["defaultValueUuid", "uuid"],
    ["defaultValueAddress", "Address"],
    ["defaultValueAge", "Age"],
    ["defaultValueAnnotation", "Annotation"],
    ["defaultValueAttachment", "Attachment"],
    ["defaultValueCodeableConcept", "CodeableConcept"],
    ["defaultValueCoding", "Coding"],
    ["defaultValueContactPoint", "ContactPoint"],
    ["defaultValueCount", "Count"],
    ["defaultValueDistance", "Distance"],
    ["defaultValueDuration", "Duration"],
    ["defaultValueHumanName", "HumanName"],
    ["defaultValueIdentifier", "Identifier"],
    ["defaultValueMoney", "Money"],
    ["defaultValuePeriod", "Period"],
    ["defaultValueQuantity", "Quantity"],
    ["defaultValueRange", "Range"],
    ["defaultValueRatio", "Ratio"],
    ["defaultValueReference", "Reference"],
    ["defaultValueSampledData", "SampledData"],
    ["defaultValueSignature", "Signature"],
    ["defaultValueTiming", "Timing"],
    ["defaultValueContactDetail", "ContactDetail"],
    ["defaultValueContributor", "Contributor"],
    ["defaultValueDataRequirement", "DataRequirement"],
    ["defaultValueExpression", "Expression"],
    ["defaultValueParameterDefinition", "ParameterDefinition"],
    ["defaultValueRelatedArtifact", "RelatedArtifact"],
    ["defaultValueTriggerDefinition", "TriggerDefinition"],
    ["defaultValueUsageContext", "UsageContext"],
    ["defaultValueDosage", "Dosage"],
    ["defaultValueMeta", "Meta"],
    ["element", "string"],
    ["listMode", "code"],
    ["logMessage", "string"],
    ["max", "string"],
    ["min", "integer"],
    ["modifierExtension", "Extension"],
    ["type", "string"],
    ["variable", "id"],
  ],
  StructureMapGroupRuleTarget: [
    ["context", "id"],
    ["contextType", "code"],
    ["element", "string"],
    ["listMode", "code"],
    ["listRuleId", "id"],
    ["modifierExtension", "Extension"],
    ["parameter", "StructureMapGroupRuleTargetParameter"],
    ["transform", "code"],
    ["variable", "id"],
  ],
  StructureMapGroupRuleTargetParameter: [
    ["modifierExtension", "Extension"],
    ["valueId", "id"],
    ["valueString", "string"],
    ["valueBoolean", "boolean"],
    ["valueInteger", "integer"],
    ["valueDecimal", "decimal"],
  ],
  StructureMapStructure: [
    ["alias", "string"],
    ["mode", "code"],
    ["modifierExtension", "Extension"],
    ["url", "canonical"],
  ],
  Subscription: [
    ["channel", "SubscriptionChannel"],
    ["contact", "ContactPoint"],
    ["criteria", "string"],
    ["end", "instant"],
    ["error", "string"],
    ["reason", "string"],
    ["status", "code"],
  ],
  SubscriptionChannel: [
    ["endpoint", "url"],
    ["header", "string"],
    ["modifierExtension", "Extension"],
    ["payload", "code"],
    ["type", "code"],
  ],
  SubscriptionStatus: [
    ["error", "CodeableConcept"],
    ["eventsSinceSubscriptionStart", "string"],
    ["status", "code"],
    ["subscription", "Reference"],
    ["topic", "canonical"],
    ["type", "code"],
  ],
  SubscriptionTopic: [
    ["canFilterBy", "SubscriptionTopicCanFilterBy"],
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["derivedFrom", "canonical"],
    ["effectivePeriod", "Period"],
    ["eventTrigger", "SubscriptionTopicEventTrigger"],
    ["experimental", "boolean"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["notificationShape", "SubscriptionTopicNotificationShape"],
    ["publisher", "string"],
    ["resourceTrigger", "SubscriptionTopicResourceTrigger"],
    ["status", "code"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  SubscriptionTopicCanFilterBy: [
    ["description", "markdown"],
    ["filterDefinition", "uri"],
    ["filterParameter", "string"],
    ["modifier", "code"],
    ["modifierExtension", "Extension"],
    ["resource", "uri"],
  ],
  SubscriptionTopicEventTrigger: [
    ["description", "markdown"],
    ["event", "CodeableConcept"],
    ["modifierExtension", "Extension"],
    ["resource", "uri"],
  ],
  SubscriptionTopicNotificationShape: [
    ["include", "string"],
    ["modifierExtension", "Extension"],
    ["resource", "uri"],
    ["revInclude", "string"],
  ],
  SubscriptionTopicResourceTrigger: [
    ["description", "markdown"],
    ["fhirPathCriteria", "string"],
    ["modifierExtension", "Extension"],
    ["queryCriteria", "SubscriptionTopicResourceTriggerQueryCriteria"],
    ["resource", "uri"],
    ["supportedInteraction", "code"],
  ],
  SubscriptionTopicResourceTriggerQueryCriteria: [
    ["current", "string"],
    ["modifierExtension", "Extension"],
    ["previous", "string"],
    ["requireBoth", "boolean"],
    ["resultForCreate", "code"],
    ["resultForDelete", "code"],
  ],
  Substance: [
    ["category", "CodeableConcept"],
    ["code", "CodeableConcept"],
    ["description", "string"],
    ["identifier", "Identifier"],
    ["ingredient", "SubstanceIngredient"],
    ["instance", "SubstanceInstance"],
    ["status", "code"],
  ],
  SubstanceIngredient: [
    ["modifierExtension", "Extension"],
    ["quantity", "Ratio"],
    ["substanceCodeableConcept", "CodeableConcept"],
    ["substanceReference", "Reference"],
  ],
  SubstanceInstance: [
    ["expiry", "dateTime"],
    ["identifier", "Identifier"],
    ["modifierExtension", "Extension"],
    ["quantity", "Quantity"],
  ],
  SubstanceDefinition: [
    ["classification", "CodeableConcept"],
    ["code", "SubstanceDefinitionCode"],
    ["description", "markdown"],
    ["domain", "CodeableConcept"],
    ["grade", "CodeableConcept"],
    ["identifier", "Identifier"],
    ["informationSource", "Reference"],
    ["manufacturer", "Reference"],
    ["moiety", "SubstanceDefinitionMoiety"],
    ["molecularWeight", "SubstanceDefinitionMolecularWeight"],
    ["name", "SubstanceDefinitionName"],
    ["note", "Annotation"],
    ["property", "SubstanceDefinitionProperty"],
    ["relationship", "SubstanceDefinitionRelationship"],
    ["sourceMaterial", "SubstanceDefinitionSourceMaterial"],
    ["status", "CodeableConcept"],
    ["structure", "SubstanceDefinitionStructure"],
    ["supplier", "Reference"],
    ["version", "string"],
  ],
  SubstanceDefinitionCode: [
    ["code", "CodeableConcept"],
    ["modifierExtension", "Extension"],
    ["note", "Annotation"],
    ["source", "Reference"],
    ["status", "CodeableConcept"],
    ["statusDate", "dateTime"],
  ],
  SubstanceDefinitionMoiety: [
    ["amountQuantity", "Quantity"],
    ["amountString", "string"],
    ["identifier", "Identifier"],
    ["measurementType", "CodeableConcept"],
    ["modifierExtension", "Extension"],
    ["molecularFormula", "string"],
    ["name", "string"],
    ["opticalActivity", "CodeableConcept"],
    ["role", "CodeableConcept"],
    ["stereochemistry", "CodeableConcept"],
  ],
  SubstanceDefinitionMolecularWeight: [
    ["amount", "Quantity"],
    ["method", "CodeableConcept"],
    ["modifierExtension", "Extension"],
    ["type", "CodeableConcept"],
  ],
  SubstanceDefinitionName: [
    ["domain", "CodeableConcept"],
    ["jurisdiction", "CodeableConcept"],
    ["language", "CodeableConcept"],
    ["modifierExtension", "Extension"],
    ["name", "string"],
    ["official", "SubstanceDefinitionNameOfficial"],
    ["preferred", "boolean"],
    ["source", "Reference"],
    ["status", "CodeableConcept"],
    ["type", "CodeableConcept"],
  ],
  SubstanceDefinitionNameOfficial: [
    ["authority", "CodeableConcept"],
    ["date", "dateTime"],
    ["modifierExtension", "Extension"],
    ["status", "CodeableConcept"],
  ],
  SubstanceDefinitionProperty: [
    ["modifierExtension", "Extension"],
    ["type", "CodeableConcept"],
    ["valueCodeableConcept", "CodeableConcept"],
    ["valueQuantity", "Quantity"],
    ["valueDate", "date"],
    ["valueBoolean", "boolean"],
    ["valueAttachment", "Attachment"],
  ],
  SubstanceDefinitionRelationship: [
    ["amountQuantity", "Quantity"],
    ["amountRatio", "Ratio"],
    ["amountString", "string"],
    ["comparator", "CodeableConcept"],
    ["isDefining", "boolean"],
    ["modifierExtension", "Extension"],
    ["ratioHighLimitAmount", "Ratio"],
    ["source", "Reference"],
    ["substanceDefinitionReference", "Reference"],
    ["substanceDefinitionCodeableConcept", "CodeableConcept"],
    ["type", "CodeableConcept"],
  ],
  SubstanceDefinitionSourceMaterial: [
    ["countryOfOrigin", "CodeableConcept"],
    ["genus", "CodeableConcept"],
    ["modifierExtension", "Extension"],
    ["part", "CodeableConcept"],
    ["species", "CodeableConcept"],
    ["type", "CodeableConcept"],
  ],
  SubstanceDefinitionStructure: [
    ["modifierExtension", "Extension"],
    ["molecularFormula", "string"],
    ["molecularFormulaByMoiety", "string"],
    ["opticalActivity", "CodeableConcept"],
    ["representation", "SubstanceDefinitionStructureRepresentation"],
    ["sourceDocument", "Reference"],
    ["stereochemistry", "CodeableConcept"],
    ["technique", "CodeableConcept"],
  ],
  SubstanceDefinitionStructureRepresentation: [
    ["document", "Reference"],
    ["format", "CodeableConcept"],
    ["modifierExtension", "Extension"],
    ["representation", "string"],
    ["type", "CodeableConcept"],
  ],
  SupplyDelivery: [
    ["basedOn", "Reference"],
    ["occurrenceDateTime", "dateTime"],
    ["occurrencePeriod", "Period"],
    ["occurrenceTiming", "Timing"],
    ["partOf", "Reference"],
    ["status", "code"],
  ],
  SupplyRequest: [
    ["authoredOn", "dateTime"],
    ["category", "CodeableConcept"],
    ["identifier", "Identifier"],
    ["itemCodeableConcept", "CodeableConcept"],
    ["itemReference", "Reference"],
    ["occurrenceDateTime", "dateTime"],
    ["occurrencePeriod", "Period"],
    ["occurrenceTiming", "Timing"],
    ["priority", "code"],
    ["quantity", "Quantity"],
    ["requester", "Reference"],
    ["status", "code"],
    ["supplier", "Reference"],
  ],
  Task: [
    ["basedOn", "Reference"],
    ["businessStatus", "CodeableConcept"],
    ["code", "CodeableConcept"],
    ["description", "string"],
    ["encounter", "Reference"],
    ["executionPeriod", "Period"],
    ["focus", "Reference"],
    ["for", "Reference"],
    ["groupIdentifier", "Identifier"],
    ["instantiatesCanonical", "canonical"],
    ["instantiatesUri", "uri"],
    ["intent", "code"],
    ["lastModified", "dateTime"],
    ["location", "Reference"],
    ["owner", "Reference"],
    ["partOf", "Reference"],
    ["requester", "Reference"],
    ["status", "code"],
    ["statusReason", "CodeableConcept"],
  ],
  TerminologyCapabilities: [
    ["contact", "ContactDetail"],
    ["copyright", "markdown"],
    ["date", "dateTime"],
    ["experimental", "boolean"],
    ["implementation", "TerminologyCapabilitiesImplementation"],
    ["jurisdiction", "CodeableConcept"],
    ["kind", "code"],
    ["lockedDate", "boolean"],
    ["name", "string"],
    ["publisher", "string"],
    ["software", "TerminologyCapabilitiesSoftware"],
    ["status", "code"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  TerminologyCapabilitiesImplementation: [
    ["description", "string"],
    ["modifierExtension", "Extension"],
    ["url", "url"],
  ],
  TerminologyCapabilitiesSoftware: [
    ["modifierExtension", "Extension"],
    ["name", "string"],
    ["version", "string"],
  ],
  TestReport: [
    ["identifier", "Identifier"],
    ["issued", "dateTime"],
    ["name", "string"],
    ["result", "code"],
    ["score", "decimal"],
    ["status", "code"],
    ["tester", "string"],
    ["testScript", "Reference"],
  ],
  TestScript: [
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["experimental", "boolean"],
    ["identifier", "Identifier"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["publisher", "string"],
    ["status", "code"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  ValueSet: [
    ["contact", "ContactDetail"],
    ["date", "dateTime"],
    ["experimental", "boolean"],
    ["identifier", "Identifier"],
    ["immutable", "boolean"],
    ["jurisdiction", "CodeableConcept"],
    ["name", "string"],
    ["publisher", "string"],
    ["status", "code"],
    ["title", "string"],
    ["url", "uri"],
    ["useContext", "UsageContext"],
    ["version", "string"],
  ],
  ValueSetComposeInclude: [
    ["filter", "ValueSetComposeIncludeFilter"],
    ["modifierExtension", "Extension"],
    ["system", "uri"],
    ["valueSet", "canonical"],
    ["version", "string"],
  ],
  ValueSetComposeIncludeFilter: [
    ["modifierExtension", "Extension"],
    ["op", "code"],
    ["property", "code"],
    ["value", "string"],
  ],
  VerificationResult: [
    ["failureAction", "CodeableConcept"],
    ["need", "CodeableConcept"],
    ["status", "code"],
    ["statusDate", "dateTime"],
    ["target", "Reference"],
    ["targetLocation", "string"],
    ["validationProcess", "CodeableConcept"],
    ["validationType", "CodeableConcept"],
  ],
  VisionPrescription: [
    ["created", "dateTime"],
    ["dateWritten", "dateTime"],
    ["lensSpecification", "VisionPrescriptionLensSpecification"],
    ["patient", "Reference"],
    ["prescriber", "Reference"],
    ["status", "code"],
  ],
  VisionPrescriptionLensSpecification: [
    ["eye", "code"],
    ["modifierExtension", "Extension"],
    ["product", "CodeableConcept"],
  ],
};

export function narrative<TResource extends AnyDomainResource>(
  resource: TResource,
  options?: NarrativeOptions | null | undefined,
): Narrative | undefined {
  const generator = NARRATIVE_GENERATORS?.[resource.resourceType];
  if (!generator) {
    return;
  }

  if (typeof generator === "function") {
    const result = generator(resource);
    if (typeof result === "string") {
      return {
        status: "generated",
        div: result,
      };
    }

    return result;
  }

  return {
    status: "generated",
    div: `<div xmlns="http://www.w3.org/1999/xhtml">${render(
      resource,
      generator,
      options,
    )}</div>`,
  };
}

function render(
  item: object,
  components: Array<NarrativeItemGenerator>,
  options: NarrativeOptions | null | undefined,
): string {
  return `<ul>${components
    .map((component) => {
      const [attribute, type] = component;

      const value = (item as any)[attribute];

      if (value == undefined) {
        return;
      }

      if (Array.isArray(value)) {
        if (value.length === 0) {
          return;
        }

        return `<li><span>${startCase(attribute)}: </span><ul>${value
          .map((i) => renderValue(i, type, options))
          .filter(Boolean)
          .map((r) => `<li>${r}</li>`)
          .join("")}</ul></li>`;
      }

      return `<li><span>${startCase(attribute).replaceAll(
        " Boolean",
        "",
      )}: </span>${renderValue(value, type, options)}</li>`;
    })
    .filter(Boolean)
    .join("")}</ul>`;
}

function renderValue(
  value: any,
  type: string,
  options: NarrativeOptions | null | undefined,
): string | undefined {
  const formatter = options?.formatter ?? Formatter.default;
  const narrativeGenerator = NARRATIVE_GENERATORS?.[type];
  if (typeof narrativeGenerator === "function") {
    const generated = narrativeGenerator(value);
    return typeof generated === "string" ? generated : generated.div;
  } else if (typeof narrativeGenerator === "object") {
    return render(value, narrativeGenerator, options);
  } else if (formatter.canFormat(type)) {
    return htmlEncode(formatter.format(type, value as never));
  }
}

function htmlEncode(value: string): string {
  return value.replaceAll(
    /[&<>\u00A0-\u9999]/g,
    (i) => "&#" + i.codePointAt(0) + ";",
  );
}
