import hb from "handlebars";
import handlebarsHelpers from "handlebars-helpers";
import Listr, { ListrTask } from "listr";
import startCase from "lodash/startCase";
import uniq from "lodash/uniq";
import uniqBy from "lodash/uniqBy";
import { readFile, writeFile } from "node:fs/promises";
import { join as pathJoin, parse as pathParse } from "node:path";
import { pushAutogeneratedNote } from "./autogenerated-note";
import { Context } from "./context";
import { elementImmediatePath } from "./helpers/element-immediate-path";
import { fhirPath } from "./helpers/fhirPath";
import { inFn } from "./helpers/in";
import { notIn } from "./helpers/not-in";
import { buildReadLines } from "./helpers/read-lines";
import { recursiveFlatten } from "./helpers/recursive-flatten";
import { replaceNewLines } from "./helpers/replace-new-lines";
import { safeNameAsVar } from "./helpers/safe-name-as-var";
import { valueSetExpansions } from "./helpers/valueSet-expansions";
import { buildWriteFiles } from "./helpers/write-files";

/**
 * For each of the template files, execute a subtask to render the template by passing
 * the current context.
 * Injects custom helpers as well:
 *  - all helpers from [handlebars-helpers](https://assemble.io/helpers/)
 *  - `startCase` from [lodash](https://lodash.com/docs/4.17.15#startCase)
 *  - `uniq` from [lodash](https://lodash.com/docs/4.17.15#uniq)
 *  - `uniqBy` from [lodash](https://lodash.com/docs/4.17.15#uniqBy)
 *  - helpers from the `helpers` directory
 */
export const ProcessTemplatesTask: ListrTask<Context> = {
  title: "Process templates",
  task: async (ctx) => {
    return new Listr<Context>(
      ctx.templates.map((element) => CreateTemplateProcessTask(element))
    );
  },
};

function CreateTemplateProcessTask(templatePath: string): ListrTask<Context> {
  const templateParsedPath = pathParse(templatePath);
  return {
    title: templateParsedPath.name,
    task: async (ctx) => {
      const compiledTemplate = hb.compile(
        await readFile(templatePath, "utf8"),
        {
          noEscape: true,
          preventIndent: true,
        }
      );

      let result = compiledTemplate(ctx, {
        helpers: {
          ...handlebarsHelpers(),
          startCase,
          uniq,
          uniqBy,
          elementImmediatePath,
          fhirPath,
          in: inFn,
          notIn,
          readLines: buildReadLines(templateParsedPath.dir),
          recursiveFlatten,
          replaceNewLines,
          safeNameAsVar,
          valueSetExpansions,
          writeFiles: buildWriteFiles(ctx, templateParsedPath.dir),
          ...ctx.helpers,
        },
      });

      if (result.trim()) {
        const targetFile = pathJoin(
          templateParsedPath.dir,
          templateParsedPath.name
        );

        result = pushAutogeneratedNote(templatePath, result, ctx.config.header);

        await writeFile(targetFile, result, { encoding: "utf8" });

        ctx.writtenFiles.push(targetFile);
      }
    },
  };
}
