/**
 * Narrative generators for r5/5.0.0
 */

/* eslint-disable @typescript-eslint/no-explicit-any */
import { AnyDomainResource, Narrative } from "./fhir-types.codegen";
import { DefaultFormatter, Formatter } from "./formatters";
import { startCase } from "./lang-utils";

/** FHIR Type, attribute name, isArray? */
export type NarrativeItemGenerator = [string, string, boolean];

export type NarrativeGenerator =
  | NarrativeItemGenerator[]
  | ((resource: any) => Narrative | string);

export const NARRATIVE_GENERATORS: Record<string, NarrativeGenerator> = {
  Account: [
    ["CodeableConcept", "billingStatus", false],
    ["markdown", "description", false],
    ["Identifier", "identifier", true],
    ["string", "name", false],
    ["Reference", "owner", false],
    ["Period", "servicePeriod", false],
    ["code", "status", false],
    ["Reference", "subject", true],
    ["CodeableConcept", "type", false],
  ],
  ActivityDefinition: [
    ["boolean", "asNeededBoolean", false],
    ["CodeableConcept", "asNeededCodeableConcept", false],
    ["CodeableConcept", "code", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["boolean", "doNotPerform", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["code", "kind", false],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  ActorDefinition: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["code", "type", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  AdministrableProductDefinition: [
    ["CodeableConcept", "administrableDoseForm", false],
    ["Reference", "device", false],
    ["Reference", "formOf", true],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "ingredient", true],
    ["Reference", "producedFrom", true],
    ["code", "status", false],
    ["CodeableConcept", "unitOfPresentation", false],
  ],
  AdverseEvent: [
    ["code", "actuality", false],
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "code", false],
    ["dateTime", "detected", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["Reference", "location", false],
    ["Annotation", "note", true],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["Timing", "occurrenceTiming", false],
    ["CodeableConcept", "outcome", true],
    ["dateTime", "recordedDate", false],
    ["Reference", "recorder", false],
    ["Reference", "resultingEffect", true],
    ["CodeableConcept", "seriousness", false],
    ["code", "status", false],
    ["Reference", "study", true],
    ["Reference", "subject", false],
  ],
  AllergyIntolerance: [
    ["code", "category", true],
    ["CodeableConcept", "clinicalStatus", false],
    ["CodeableConcept", "code", false],
    ["code", "criticality", false],
    ["Identifier", "identifier", true],
    ["Reference", "patient", false],
    ["CodeableConcept", "type", false],
    ["CodeableConcept", "verificationStatus", false],
  ],
  Appointment: [
    ["CodeableConcept", "appointmentType", false],
    ["CodeableConcept", "cancellationReason", false],
    ["CodeableConcept", "class", true],
    ["instant", "end", false],
    ["Identifier", "identifier", true],
    ["CodeableReference", "reason", true],
    ["CodeableConcept", "serviceCategory", true],
    ["CodeableReference", "serviceType", true],
    ["CodeableConcept", "specialty", true],
    ["instant", "start", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  AppointmentResponse: [
    ["Reference", "actor", false],
    ["Reference", "appointment", false],
    ["Identifier", "identifier", true],
    ["code", "participantStatus", false],
    ["CodeableConcept", "participantType", true],
    ["boolean", "proposedNewTime", false],
  ],
  ArtifactAssessment: [
    ["Reference", "artifactReference", false],
    ["canonical", "artifactCanonical", false],
    ["uri", "artifactUri", false],
    ["dateTime", "date", false],
    ["code", "disposition", false],
    ["Identifier", "identifier", true],
    ["date", "lastReviewDate", false],
    ["string", "title", false],
    ["code", "workflowStatus", false],
  ],
  AuditEvent: [
    ["code", "action", false],
    ["CodeableConcept", "authorization", true],
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "code", false],
    ["instant", "recorded", false],
    ["code", "severity", false],
  ],
  Basic: [
    ["Reference", "author", false],
    ["CodeableConcept", "code", false],
    ["dateTime", "created", false],
    ["Identifier", "identifier", true],
    ["Reference", "subject", false],
  ],
  BiologicallyDerivedProduct: [
    ["Identifier", "biologicalSourceEvent", false],
    ["Identifier", "identifier", true],
  ],
  BiologicallyDerivedProductDispense: [
    ["Reference", "basedOn", true],
    ["Reference", "destination", false],
    ["Identifier", "identifier", true],
    ["Reference", "location", false],
    ["CodeableConcept", "matchStatus", false],
    ["Annotation", "note", true],
    ["CodeableConcept", "originRelationshipType", false],
    ["Reference", "partOf", true],
    ["Reference", "patient", false],
    ["dateTime", "preparedDate", false],
    ["Reference", "product", false],
    ["Quantity", "quantity", false],
    ["code", "status", false],
    ["string", "usageInstruction", false],
    ["dateTime", "whenHandedOver", false],
  ],
  BodyStructure: [
    ["boolean", "active", false],
    ["markdown", "description", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "morphology", false],
    ["Reference", "patient", false],
  ],
  CanonicalResource: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  CapabilityStatement: [
    ["code", "acceptLanguage", true],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["code", "fhirVersion", false],
    ["code", "format", true],
    ["Identifier", "identifier", true],
    ["canonical", "implementationGuide", true],
    ["canonical", "imports", true],
    ["canonical", "instantiates", true],
    ["CodeableConcept", "jurisdiction", true],
    ["code", "kind", false],
    ["string", "name", false],
    ["code", "patchFormat", true],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  CarePlan: [
    ["CodeableReference", "addresses", true],
    ["Reference", "basedOn", true],
    ["CodeableConcept", "category", true],
    ["dateTime", "created", false],
    ["Reference", "custodian", false],
    ["string", "description", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["code", "intent", false],
    ["Reference", "partOf", true],
    ["Period", "period", false],
    ["Reference", "replaces", true],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["string", "title", false],
  ],
  CareTeam: [
    ["CodeableConcept", "category", true],
    ["Identifier", "identifier", true],
    ["Reference", "managingOrganization", true],
    ["string", "name", false],
    ["Period", "period", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  ChargeItem: [
    ["Reference", "account", true],
    ["CodeableConcept", "bodysite", true],
    ["CodeableConcept", "code", false],
    ["Reference", "encounter", false],
    ["dateTime", "enteredDate", false],
    ["Reference", "enterer", false],
    ["Identifier", "identifier", true],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["Timing", "occurrenceTiming", false],
    ["Quantity", "quantity", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  ChargeItemDefinition: [
    ["CodeableConcept", "code", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["uri", "derivedFromUri", true],
    ["markdown", "description", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["canonical", "partOf", true],
    ["string", "publisher", false],
    ["canonical", "replaces", true],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  Citation: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  Claim: [
    ["Period", "billablePeriod", false],
    ["dateTime", "created", false],
    ["Reference", "insurer", false],
    ["Reference", "patient", false],
    ["CodeableConcept", "priority", false],
    ["Reference", "provider", false],
    ["code", "status", false],
    ["CodeableConcept", "type", false],
    ["code", "use", false],
  ],
  ClaimResponse: [
    ["dateTime", "created", false],
    ["CodeableConcept", "decision", false],
    ["Reference", "insurer", false],
    ["code", "outcome", false],
    ["Reference", "patient", false],
    ["Reference", "request", false],
    ["code", "status", false],
    ["CodeableConcept", "type", false],
    ["code", "use", false],
  ],
  ClinicalImpression: [
    ["dateTime", "date", false],
    ["string", "description", false],
    ["dateTime", "effectiveDateTime", false],
    ["Period", "effectivePeriod", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["Reference", "performer", false],
    ["Reference", "problem", true],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  ClinicalUseDefinition: [
    ["CodeableConcept", "category", true],
    ["Identifier", "identifier", true],
    ["canonical", "library", true],
    ["Reference", "population", true],
    ["CodeableConcept", "status", false],
    ["Reference", "subject", true],
    ["code", "type", false],
  ],
  CodeSystem: [
    ["boolean", "caseSensitive", false],
    ["boolean", "compositional", false],
    ["ContactDetail", "contact", true],
    ["code", "content", false],
    ["unsignedInt", "count", false],
    ["dateTime", "date", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["code", "hierarchyMeaning", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["canonical", "supplements", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["canonical", "valueSet", false],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
    ["boolean", "versionNeeded", false],
  ],
  Communication: [
    ["Reference", "basedOn", true],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["Reference", "partOf", true],
    ["code", "priority", false],
    ["CodeableReference", "reason", true],
    ["code", "status", false],
    ["CodeableConcept", "statusReason", false],
    ["Reference", "subject", false],
  ],
  CommunicationRequest: [
    ["dateTime", "authoredOn", false],
    ["Reference", "basedOn", true],
    ["boolean", "doNotPerform", false],
    ["Reference", "encounter", false],
    ["Identifier", "groupIdentifier", false],
    ["Identifier", "identifier", true],
    ["Reference", "informationProvider", true],
    ["code", "intent", false],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["code", "priority", false],
    ["CodeableReference", "reason", true],
    ["Reference", "replaces", true],
    ["Reference", "requester", false],
    ["code", "status", false],
  ],
  CompartmentDefinition: [
    ["code", "code", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["string", "name", false],
    ["string", "publisher", false],
    ["boolean", "search", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  Composition: [
    ["Reference", "author", true],
    ["CodeableConcept", "category", true],
    ["Reference", "custodian", false],
    ["dateTime", "date", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["string", "name", false],
    ["code", "status", false],
    ["Reference", "subject", true],
    ["string", "title", false],
    ["CodeableConcept", "type", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
  ],
  ConceptMap: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["uri", "sourceScopeUri", false],
    ["canonical", "sourceScopeCanonical", false],
    ["code", "status", false],
    ["uri", "targetScopeUri", false],
    ["canonical", "targetScopeCanonical", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  Condition: [
    ["CodeableConcept", "bodySite", true],
    ["CodeableConcept", "clinicalStatus", false],
    ["CodeableConcept", "code", false],
    ["Reference", "encounter", false],
    ["CodeableReference", "evidence", true],
    ["Identifier", "identifier", true],
    ["dateTime", "onsetDateTime", false],
    ["Age", "onsetAge", false],
    ["Period", "onsetPeriod", false],
    ["Range", "onsetRange", false],
    ["string", "onsetString", false],
    ["dateTime", "recordedDate", false],
    ["Reference", "subject", false],
    ["CodeableConcept", "verificationStatus", false],
  ],
  ConditionDefinition: [
    ["CodeableConcept", "bodySite", false],
    ["CodeableConcept", "code", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["CodeableConcept", "severity", false],
    ["CodeableConcept", "stage", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  Consent: [
    ["CodeableConcept", "category", true],
    ["date", "date", false],
    ["code", "decision", false],
    ["Reference", "grantee", true],
    ["Reference", "grantor", true],
    ["Identifier", "identifier", true],
    ["Period", "period", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  Contract: [
    ["Period", "applies", false],
    ["Identifier", "identifier", true],
    ["dateTime", "issued", false],
    ["string", "name", false],
    ["code", "status", false],
    ["Reference", "subject", true],
    ["CodeableConcept", "subType", true],
    ["string", "title", false],
    ["CodeableConcept", "type", false],
    ["string", "version", false],
  ],
  Coverage: [
    ["Reference", "beneficiary", false],
    ["string", "dependent", false],
    ["Identifier", "identifier", true],
    ["Reference", "insurer", false],
    ["code", "kind", false],
    ["string", "network", false],
    ["positiveInt", "order", false],
    ["Period", "period", false],
    ["Reference", "policyHolder", false],
    ["code", "status", false],
    ["Reference", "subscriber", false],
    ["Identifier", "subscriberId", true],
    ["CodeableConcept", "type", false],
  ],
  CoverageEligibilityRequest: [
    ["dateTime", "created", false],
    ["Reference", "insurer", false],
    ["Reference", "patient", false],
    ["code", "purpose", true],
    ["code", "status", false],
  ],
  CoverageEligibilityResponse: [
    ["dateTime", "created", false],
    ["Reference", "insurer", false],
    ["code", "outcome", false],
    ["Reference", "patient", false],
    ["code", "purpose", true],
    ["Reference", "request", false],
    ["code", "status", false],
  ],
  DetectedIssue: [
    ["Reference", "author", false],
    ["CodeableConcept", "code", false],
    ["Reference", "encounter", false],
    ["dateTime", "identifiedDateTime", false],
    ["Period", "identifiedPeriod", false],
    ["Identifier", "identifier", true],
    ["Reference", "implicated", true],
    ["code", "severity", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  Device: [
    ["CodeableConcept", "safety", true],
    ["code", "status", false],
  ],
  DeviceAssociation: [
    ["Reference", "bodyStructure", false],
    ["CodeableConcept", "category", true],
    ["Reference", "device", false],
    ["Identifier", "identifier", true],
    ["Period", "period", false],
    ["CodeableConcept", "status", false],
    ["CodeableConcept", "statusReason", true],
    ["Reference", "subject", false],
  ],
  DeviceDefinition: [
    ["Identifier", "identifier", true],
    ["Reference", "manufacturer", false],
    ["string", "modelNumber", false],
    ["CodeableConcept", "safety", true],
  ],
  DeviceDispense: [
    ["CodeableReference", "device", false],
    ["Identifier", "identifier", true],
    ["dateTime", "preparedDate", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  DeviceMetric: [
    ["code", "category", false],
    ["Reference", "device", false],
    ["Identifier", "identifier", true],
    ["code", "operationalStatus", false],
    ["CodeableConcept", "type", false],
    ["CodeableConcept", "unit", false],
  ],
  DeviceRequest: [
    ["dateTime", "authoredOn", false],
    ["Reference", "basedOn", true],
    ["CodeableReference", "code", false],
    ["boolean", "doNotPerform", false],
    ["Reference", "encounter", false],
    ["Identifier", "groupIdentifier", false],
    ["Identifier", "identifier", true],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["code", "intent", false],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["Timing", "occurrenceTiming", false],
    ["CodeableReference", "performer", false],
    ["code", "priority", false],
    ["CodeableReference", "reason", true],
    ["Reference", "replaces", true],
    ["Reference", "requester", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  DeviceUsage: [
    ["Reference", "basedOn", true],
    ["CodeableReference", "bodySite", false],
    ["Reference", "context", false],
    ["dateTime", "dateAsserted", false],
    ["Reference", "derivedFrom", true],
    ["CodeableReference", "device", false],
    ["Identifier", "identifier", true],
    ["Reference", "informationSource", false],
    ["Reference", "patient", false],
    ["CodeableReference", "reason", true],
    ["code", "status", false],
    ["Timing", "timingTiming", false],
    ["Period", "timingPeriod", false],
    ["dateTime", "timingDateTime", false],
  ],
  DiagnosticReport: [
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "code", false],
    ["dateTime", "effectiveDateTime", false],
    ["Period", "effectivePeriod", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["instant", "issued", false],
    ["Reference", "performer", true],
    ["Reference", "resultsInterpreter", true],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  DocumentReference: [
    ["Reference", "author", true],
    ["CodeableReference", "bodySite", true],
    ["CodeableConcept", "category", true],
    ["instant", "date", false],
    ["markdown", "description", false],
    ["code", "docStatus", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "modality", true],
    ["Period", "period", false],
    ["CodeableConcept", "securityLabel", true],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["CodeableConcept", "type", false],
    ["string", "version", false],
  ],
  Encounter: [
    ["Reference", "appointment", true],
    ["CodeableConcept", "class", true],
    ["Reference", "episodeOfCare", true],
    ["Identifier", "identifier", true],
    ["CodeableReference", "serviceType", true],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["CodeableConcept", "type", true],
  ],
  EncounterHistory: [
    ["CodeableConcept", "class", false],
    ["Identifier", "identifier", true],
    ["CodeableReference", "serviceType", true],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["CodeableConcept", "type", true],
  ],
  Endpoint: [
    ["url", "address", false],
    ["CodeableConcept", "connectionType", true],
    ["string", "description", false],
    ["CodeableConcept", "environmentType", true],
    ["Identifier", "identifier", true],
    ["Reference", "managingOrganization", false],
    ["string", "name", false],
    ["Period", "period", false],
    ["code", "status", false],
  ],
  EnrollmentRequest: [["code", "status", false]],
  EnrollmentResponse: [["code", "status", false]],
  EpisodeOfCare: [
    ["Reference", "managingOrganization", false],
    ["Reference", "patient", false],
    ["Period", "period", false],
    ["code", "status", false],
    ["CodeableConcept", "type", true],
  ],
  EventDefinition: [
    ["date", "approvalDate", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["date", "lastReviewDate", false],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["TriggerDefinition", "trigger", true],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  Evidence: [
    ["ContactDetail", "author", true],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["ContactDetail", "endorser", true],
    ["Identifier", "identifier", true],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  EvidenceReport: [
    ["ContactDetail", "author", true],
    ["ContactDetail", "contact", true],
    ["ContactDetail", "endorser", true],
    ["Identifier", "identifier", true],
    ["string", "publisher", false],
    ["Identifier", "relatedIdentifier", true],
    ["code", "status", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
  ],
  EvidenceVariable: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["Identifier", "identifier", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["string", "shortTitle", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  ExampleScenario: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  ExplanationOfBenefit: [
    ["Period", "billablePeriod", false],
    ["dateTime", "created", false],
    ["CodeableConcept", "decision", false],
    ["Reference", "insurer", false],
    ["code", "outcome", false],
    ["Reference", "patient", false],
    ["Reference", "provider", false],
    ["code", "status", false],
    ["CodeableConcept", "type", false],
    ["code", "use", false],
  ],
  FamilyMemberHistory: [
    ["Age", "ageAge", false],
    ["Range", "ageRange", false],
    ["string", "ageString", false],
    ["CodeableConcept", "dataAbsentReason", false],
    ["dateTime", "date", false],
    ["boolean", "deceasedBoolean", false],
    ["Age", "deceasedAge", false],
    ["Range", "deceasedRange", false],
    ["date", "deceasedDate", false],
    ["string", "deceasedString", false],
    ["boolean", "estimatedAge", false],
    ["Identifier", "identifier", true],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["string", "name", false],
    ["Reference", "patient", false],
    ["CodeableReference", "reason", true],
    ["CodeableConcept", "relationship", false],
    ["CodeableConcept", "sex", false],
    ["code", "status", false],
  ],
  Flag: [
    ["Reference", "author", false],
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "code", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["Period", "period", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  FormularyItem: [
    ["CodeableConcept", "code", false],
    ["Identifier", "identifier", true],
    ["code", "status", false],
  ],
  GenomicStudy: [
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["CodeableConcept", "type", true],
  ],
  Goal: [
    ["CodeableConcept", "achievementStatus", false],
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "description", false],
    ["code", "lifecycleStatus", false],
    ["CodeableConcept", "priority", false],
    ["Reference", "source", false],
    ["date", "startDate", false],
    ["CodeableConcept", "startCodeableConcept", false],
    ["date", "statusDate", false],
    ["Reference", "subject", false],
  ],
  GraphDefinition: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  Group: [
    ["boolean", "active", false],
    ["CodeableConcept", "code", false],
    ["Identifier", "identifier", true],
    ["Reference", "managingEntity", false],
    ["code", "membership", false],
    ["string", "name", false],
    ["unsignedInt", "quantity", false],
    ["code", "type", false],
  ],
  GuidanceResponse: [
    ["Identifier", "identifier", true],
    ["uri", "moduleUri", false],
    ["canonical", "moduleCanonical", false],
    ["CodeableConcept", "moduleCodeableConcept", false],
    ["Identifier", "requestIdentifier", false],
    ["code", "status", false],
  ],
  HealthcareService: [
    ["boolean", "active", false],
    ["CodeableConcept", "category", true],
    ["markdown", "comment", false],
    ["Identifier", "identifier", true],
    ["Reference", "location", true],
    ["string", "name", false],
    ["Attachment", "photo", false],
    ["Reference", "providedBy", false],
    ["CodeableConcept", "specialty", true],
    ["CodeableConcept", "type", true],
  ],
  ImagingSelection: [
    ["Reference", "basedOn", true],
    ["CodeableReference", "bodySite", false],
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "code", false],
    ["Reference", "derivedFrom", true],
    ["Reference", "endpoint", true],
    ["Reference", "focus", true],
    ["id", "frameOfReferenceUid", false],
    ["Identifier", "identifier", true],
    ["instant", "issued", false],
    ["unsignedInt", "seriesNumber", false],
    ["id", "seriesUid", false],
    ["code", "status", false],
    ["id", "studyUid", false],
    ["Reference", "subject", false],
  ],
  ImagingStudy: [
    ["Reference", "basedOn", true],
    ["string", "description", false],
    ["Reference", "encounter", false],
    ["Reference", "endpoint", true],
    ["Identifier", "identifier", true],
    ["Reference", "location", false],
    ["CodeableConcept", "modality", true],
    ["Annotation", "note", true],
    ["unsignedInt", "numberOfInstances", false],
    ["unsignedInt", "numberOfSeries", false],
    ["Reference", "partOf", true],
    ["CodeableReference", "procedure", true],
    ["CodeableReference", "reason", true],
    ["Reference", "referrer", false],
    ["dateTime", "started", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  Immunization: [
    ["Reference", "basedOn", true],
    ["boolean", "isSubpotent", false],
    ["Annotation", "note", true],
    ["dateTime", "occurrenceDateTime", false],
    ["string", "occurrenceString", false],
    ["Reference", "patient", false],
    ["boolean", "primarySource", false],
    ["code", "status", false],
    ["CodeableConcept", "vaccineCode", false],
  ],
  ImmunizationEvaluation: [
    ["CodeableConcept", "doseStatus", false],
    ["Reference", "immunizationEvent", false],
    ["Reference", "patient", false],
    ["code", "status", false],
    ["CodeableConcept", "targetDisease", false],
  ],
  ImmunizationRecommendation: [
    ["dateTime", "date", false],
    ["Identifier", "identifier", true],
    ["Reference", "patient", false],
  ],
  ImplementationGuide: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["code", "fhirVersion", true],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["code", "license", false],
    ["string", "name", false],
    ["id", "packageId", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  Ingredient: [
    ["boolean", "allergenicIndicator", false],
    ["Reference", "for", true],
    ["CodeableConcept", "function", true],
    ["CodeableConcept", "group", false],
    ["Identifier", "identifier", false],
    ["CodeableConcept", "role", false],
    ["code", "status", false],
  ],
  InsurancePlan: [
    ["Reference", "administeredBy", false],
    ["Reference", "coverageArea", true],
    ["Identifier", "identifier", true],
    ["string", "name", false],
    ["Reference", "ownedBy", false],
    ["code", "status", false],
    ["CodeableConcept", "type", true],
  ],
  InventoryItem: [
    ["CodeableConcept", "baseUnit", false],
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "code", true],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "inventoryStatus", true],
    ["Quantity", "netContent", false],
    ["code", "status", false],
  ],
  InventoryReport: [
    ["code", "countType", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "operationType", false],
    ["CodeableConcept", "operationTypeReason", false],
    ["dateTime", "reportedDateTime", false],
    ["code", "status", false],
  ],
  Invoice: [
    ["dateTime", "creation", false],
    ["Identifier", "identifier", true],
    ["date", "periodDate", false],
    ["Period", "periodPeriod", false],
    ["Reference", "recipient", false],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["Money", "totalGross", false],
    ["Money", "totalNet", false],
    ["CodeableConcept", "type", false],
  ],
  Library: [
    ["ContactDetail", "contact", true],
    ["Attachment", "content", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["CodeableConcept", "type", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  Linkage: [
    ["boolean", "active", false],
    ["Reference", "author", false],
  ],
  List: [
    ["CodeableConcept", "code", false],
    ["dateTime", "date", false],
    ["code", "mode", false],
    ["Reference", "source", false],
    ["code", "status", false],
    ["Reference", "subject", true],
    ["string", "title", false],
  ],
  Location: [
    ["markdown", "description", false],
    ["CodeableConcept", "form", false],
    ["Identifier", "identifier", true],
    ["Reference", "managingOrganization", false],
    ["code", "mode", false],
    ["string", "name", false],
    ["Coding", "operationalStatus", false],
    ["code", "status", false],
    ["CodeableConcept", "type", true],
  ],
  ManufacturedItemDefinition: [
    ["Identifier", "identifier", true],
    ["CodeableConcept", "ingredient", true],
    ["CodeableConcept", "manufacturedDoseForm", false],
    ["Reference", "manufacturer", true],
    ["MarketingStatus", "marketingStatus", true],
    ["string", "name", false],
    ["code", "status", false],
    ["CodeableConcept", "unitOfPresentation", false],
  ],
  Measure: [
    ["code", "basis", false],
    ["markdown", "clinicalRecommendationStatement", false],
    ["CodeableConcept", "compositeScoring", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["markdown", "disclaimer", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["markdown", "guidance", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "improvementNotation", false],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["markdown", "rateAggregation", false],
    ["markdown", "rationale", false],
    ["markdown", "riskAdjustment", false],
    ["CodeableConcept", "scoring", false],
    ["CodeableConcept", "scoringUnit", false],
    ["code", "status", false],
    ["string", "title", false],
    ["CodeableConcept", "type", true],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  MeasureReport: [
    ["code", "dataUpdateType", false],
    ["dateTime", "date", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "improvementNotation", false],
    ["canonical", "measure", false],
    ["Period", "period", false],
    ["Reference", "reporter", false],
    ["CodeableConcept", "scoring", false],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["code", "type", false],
  ],
  Medication: [
    ["CodeableConcept", "code", false],
    ["Identifier", "identifier", true],
    ["Reference", "marketingAuthorizationHolder", false],
    ["code", "status", false],
    ["Quantity", "totalVolume", false],
  ],
  MedicationAdministration: [
    ["CodeableReference", "medication", false],
    ["dateTime", "occurenceDateTime", false],
    ["Period", "occurencePeriod", false],
    ["Timing", "occurenceTiming", false],
    ["Reference", "partOf", true],
    ["dateTime", "recorded", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  MedicationDispense: [
    ["CodeableReference", "medication", false],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["dateTime", "whenPrepared", false],
  ],
  MedicationKnowledge: [
    ["CodeableConcept", "code", false],
    ["Identifier", "identifier", true],
    ["string", "name", true],
    ["code", "status", false],
  ],
  MedicationRequest: [
    ["dateTime", "authoredOn", false],
    ["Reference", "basedOn", true],
    ["boolean", "doNotPerform", false],
    ["Identifier", "groupIdentifier", false],
    ["code", "intent", false],
    ["CodeableReference", "medication", false],
    ["CodeableConcept", "performerType", false],
    ["code", "priority", false],
    ["boolean", "reported", false],
    ["Reference", "requester", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  MedicationStatement: [
    ["CodeableConcept", "category", true],
    ["dateTime", "dateAsserted", false],
    ["dateTime", "effectiveDateTime", false],
    ["Period", "effectivePeriod", false],
    ["Timing", "effectiveTiming", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["CodeableReference", "medication", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  MedicinalProductDefinition: [
    ["CodeableConcept", "additionalMonitoringIndicator", false],
    ["Reference", "attachedDocument", true],
    ["CodeableConcept", "classification", true],
    ["Reference", "clinicalTrial", true],
    ["Coding", "code", true],
    ["CodeableConcept", "combinedPharmaceuticalDoseForm", false],
    ["Reference", "comprisedOf", true],
    ["markdown", "description", false],
    ["CodeableConcept", "domain", false],
    ["Identifier", "identifier", true],
    ["CodeableReference", "impurity", true],
    ["markdown", "indication", false],
    ["CodeableConcept", "ingredient", true],
    ["CodeableConcept", "legalStatusOfSupply", false],
    ["MarketingStatus", "marketingStatus", true],
    ["Reference", "masterFile", true],
    ["CodeableConcept", "packagedMedicinalProduct", true],
    ["CodeableConcept", "pediatricUseIndicator", false],
    ["CodeableConcept", "route", true],
    ["CodeableConcept", "specialMeasures", true],
    ["CodeableConcept", "status", false],
    ["dateTime", "statusDate", false],
    ["CodeableConcept", "type", false],
    ["string", "version", false],
  ],
  MessageDefinition: [
    ["canonical", "base", false],
    ["code", "category", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["Coding", "eventCoding", false],
    ["uri", "eventUri", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["canonical", "parent", true],
    ["string", "publisher", false],
    ["markdown", "purpose", false],
    ["canonical", "replaces", true],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  MessageHeader: [
    ["Reference", "author", false],
    ["canonical", "definition", false],
    ["Coding", "eventCoding", false],
    ["canonical", "eventCanonical", false],
    ["Reference", "focus", true],
    ["CodeableConcept", "reason", false],
    ["Reference", "responsible", false],
    ["Reference", "sender", false],
  ],
  MetadataResource: [["Period", "effectivePeriod", false]],
  MolecularSequence: [
    ["Reference", "device", false],
    ["Reference", "focus", true],
    ["Attachment", "formatted", true],
    ["Identifier", "identifier", true],
    ["string", "literal", false],
    ["Reference", "performer", false],
    ["Reference", "specimen", false],
    ["Reference", "subject", false],
    ["code", "type", false],
  ],
  NamingSystem: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["code", "kind", false],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  NutritionIntake: [
    ["Reference", "basedOn", true],
    ["CodeableConcept", "code", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["Reference", "partOf", true],
    ["dateTime", "recorded", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  NutritionOrder: [
    ["dateTime", "dateTime", false],
    ["Identifier", "groupIdentifier", false],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["code", "intent", false],
    ["Reference", "orderer", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  NutritionProduct: [
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "code", false],
    ["Reference", "manufacturer", true],
    ["code", "status", false],
  ],
  Observation: [
    ["Reference", "basedOn", true],
    ["CodeableConcept", "code", false],
    ["Reference", "derivedFrom", true],
    ["dateTime", "effectiveDateTime", false],
    ["Period", "effectivePeriod", false],
    ["Timing", "effectiveTiming", false],
    ["instant", "effectiveInstant", false],
    ["Reference", "encounter", false],
    ["Reference", "focus", true],
    ["Reference", "hasMember", true],
    ["Identifier", "identifier", true],
    ["canonical", "instantiatesCanonical", false],
    ["Reference", "instantiatesReference", false],
    ["instant", "issued", false],
    ["Reference", "partOf", true],
    ["Reference", "performer", true],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["Quantity", "valueQuantity", false],
    ["CodeableConcept", "valueCodeableConcept", false],
    ["string", "valueString", false],
    ["boolean", "valueBoolean", false],
    ["integer", "valueInteger", false],
    ["Range", "valueRange", false],
    ["Ratio", "valueRatio", false],
    ["SampledData", "valueSampledData", false],
    ["time", "valueTime", false],
    ["dateTime", "valueDateTime", false],
    ["Period", "valuePeriod", false],
    ["Attachment", "valueAttachment", false],
    ["Reference", "valueReference", false],
  ],
  ObservationDefinition: [
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "code", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["canonical", "derivedFromCanonical", true],
    ["uri", "derivedFromUri", true],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", false],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["CodeableConcept", "performerType", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["CodeableConcept", "subject", true],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  OperationDefinition: [
    ["boolean", "affectsState", false],
    ["canonical", "base", false],
    ["code", "code", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["boolean", "instance", false],
    ["CodeableConcept", "jurisdiction", true],
    ["code", "kind", false],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "resource", true],
    ["code", "status", false],
    ["boolean", "system", false],
    ["string", "title", false],
    ["boolean", "type", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  OperationOutcome: [],
  Organization: [
    ["boolean", "active", false],
    ["markdown", "description", false],
    ["Identifier", "identifier", true],
    ["string", "name", false],
    ["Reference", "partOf", false],
    ["CodeableConcept", "type", true],
  ],
  OrganizationAffiliation: [
    ["boolean", "active", false],
    ["CodeableConcept", "code", true],
    ["Identifier", "identifier", true],
    ["Reference", "location", true],
    ["Reference", "network", true],
    ["Reference", "organization", false],
    ["Reference", "participatingOrganization", false],
    ["Period", "period", false],
    ["CodeableConcept", "specialty", true],
  ],
  PackagedProductDefinition: [
    ["Reference", "attachedDocument", true],
    ["Quantity", "containedItemQuantity", true],
    ["boolean", "copackagedIndicator", false],
    ["markdown", "description", false],
    ["Identifier", "identifier", true],
    ["Reference", "manufacturer", true],
    ["MarketingStatus", "marketingStatus", true],
    ["string", "name", false],
    ["Reference", "packageFor", true],
    ["CodeableConcept", "status", false],
    ["dateTime", "statusDate", false],
    ["CodeableConcept", "type", false],
  ],
  Patient: [
    ["boolean", "active", false],
    ["Address", "address", true],
    ["date", "birthDate", false],
    ["boolean", "deceasedBoolean", false],
    ["dateTime", "deceasedDateTime", false],
    ["code", "gender", false],
    ["Identifier", "identifier", true],
    ["Reference", "managingOrganization", false],
    ["HumanName", "name", true],
    ["ContactPoint", "telecom", true],
  ],
  PaymentNotice: [
    ["Money", "amount", false],
    ["dateTime", "created", false],
    ["Reference", "payment", false],
    ["Reference", "recipient", false],
    ["code", "status", false],
  ],
  PaymentReconciliation: [
    ["Money", "amount", false],
    ["dateTime", "created", false],
    ["date", "date", false],
    ["Reference", "paymentIssuer", false],
    ["Period", "period", false],
    ["code", "status", false],
    ["CodeableConcept", "type", false],
  ],
  Permission: [
    ["Reference", "asserter", false],
    ["code", "combining", false],
    ["dateTime", "date", true],
    ["code", "status", false],
    ["Period", "validity", false],
  ],
  Person: [
    ["boolean", "active", false],
    ["Address", "address", true],
    ["date", "birthDate", false],
    ["boolean", "deceasedBoolean", false],
    ["dateTime", "deceasedDateTime", false],
    ["code", "gender", false],
    ["Identifier", "identifier", true],
    ["Reference", "managingOrganization", false],
    ["HumanName", "name", true],
    ["ContactPoint", "telecom", true],
  ],
  PlanDefinition: [
    ["boolean", "asNeededBoolean", false],
    ["CodeableConcept", "asNeededCodeableConcept", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["CodeableConcept", "type", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  Practitioner: [
    ["boolean", "active", false],
    ["Address", "address", true],
    ["date", "birthDate", false],
    ["boolean", "deceasedBoolean", false],
    ["dateTime", "deceasedDateTime", false],
    ["code", "gender", false],
    ["Identifier", "identifier", true],
    ["HumanName", "name", true],
    ["ContactPoint", "telecom", true],
  ],
  PractitionerRole: [
    ["boolean", "active", false],
    ["CodeableConcept", "code", true],
    ["Identifier", "identifier", true],
    ["Reference", "location", true],
    ["Reference", "organization", false],
    ["Period", "period", false],
    ["Reference", "practitioner", false],
    ["CodeableConcept", "specialty", true],
  ],
  Procedure: [
    ["Reference", "basedOn", true],
    ["CodeableConcept", "bodySite", true],
    ["CodeableConcept", "category", true],
    ["CodeableConcept", "code", false],
    ["Reference", "encounter", false],
    ["Reference", "focus", false],
    ["Identifier", "identifier", true],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["Reference", "location", false],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["string", "occurrenceString", false],
    ["Age", "occurrenceAge", false],
    ["Range", "occurrenceRange", false],
    ["Timing", "occurrenceTiming", false],
    ["CodeableConcept", "outcome", false],
    ["Reference", "partOf", true],
    ["CodeableReference", "reason", true],
    ["dateTime", "recorded", false],
    ["Reference", "recorder", false],
    ["boolean", "reportedBoolean", false],
    ["Reference", "reportedReference", false],
    ["code", "status", false],
    ["CodeableConcept", "statusReason", false],
    ["Reference", "subject", false],
  ],
  Provenance: [
    ["instant", "recorded", false],
    ["Reference", "target", true],
  ],
  Questionnaire: [
    ["Coding", "code", true],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["canonical", "derivedFrom", true],
    ["markdown", "description", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["code", "subjectType", true],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  QuestionnaireResponse: [
    ["Reference", "author", false],
    ["dateTime", "authored", false],
    ["Reference", "basedOn", true],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["Reference", "partOf", true],
    ["canonical", "questionnaire", false],
    ["Reference", "source", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  RegulatedAuthorization: [
    ["Reference", "attachedDocument", true],
    ["CodeableConcept", "basis", true],
    ["markdown", "description", false],
    ["Reference", "holder", false],
    ["Identifier", "identifier", true],
    ["CodeableReference", "indication", true],
    ["CodeableConcept", "intendedUse", false],
    ["CodeableConcept", "region", true],
    ["Reference", "regulator", false],
    ["CodeableConcept", "status", false],
    ["dateTime", "statusDate", false],
    ["Reference", "subject", true],
    ["CodeableConcept", "type", false],
    ["Period", "validityPeriod", false],
  ],
  RelatedPerson: [
    ["boolean", "active", false],
    ["Address", "address", true],
    ["date", "birthDate", false],
    ["code", "gender", false],
    ["Identifier", "identifier", true],
    ["HumanName", "name", true],
    ["Reference", "patient", false],
    ["CodeableConcept", "relationship", true],
    ["ContactPoint", "telecom", true],
  ],
  RequestOrchestration: [
    ["CodeableConcept", "code", false],
    ["Identifier", "groupIdentifier", false],
    ["Identifier", "identifier", true],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["code", "intent", false],
    ["code", "priority", false],
    ["code", "status", false],
  ],
  Requirements: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["canonical", "derivedFrom", true],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  ResearchStudy: [
    ["CodeableConcept", "condition", true],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "keyword", true],
    ["Reference", "partOf", true],
    ["Period", "period", false],
    ["CodeableConcept", "phase", false],
    ["CodeableConcept", "primaryPurposeType", false],
    ["Reference", "protocol", true],
    ["CodeableConcept", "region", true],
    ["Reference", "result", true],
    ["Reference", "site", true],
    ["code", "status", false],
    ["CodeableConcept", "studyDesign", true],
    ["string", "title", false],
    ["CodeableConcept", "whyStopped", false],
  ],
  ResearchSubject: [
    ["Identifier", "identifier", true],
    ["Period", "period", false],
    ["code", "status", false],
    ["Reference", "study", false],
    ["Reference", "subject", false],
  ],
  RiskAssessment: [
    ["CodeableConcept", "code", false],
    ["Reference", "condition", false],
    ["Reference", "encounter", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "method", false],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["Reference", "performer", false],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  Schedule: [
    ["boolean", "active", false],
    ["Reference", "actor", true],
    ["Identifier", "identifier", true],
    ["string", "name", false],
    ["Period", "planningHorizon", false],
    ["CodeableConcept", "serviceCategory", true],
    ["CodeableReference", "serviceType", true],
    ["CodeableConcept", "specialty", true],
  ],
  SearchParameter: [
    ["code", "base", true],
    ["code", "code", false],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["markdown", "description", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["code", "type", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  ServiceRequest: [
    ["boolean", "asNeededBoolean", false],
    ["CodeableConcept", "asNeededCodeableConcept", false],
    ["dateTime", "authoredOn", false],
    ["Reference", "basedOn", true],
    ["CodeableConcept", "bodySite", true],
    ["Reference", "bodyStructure", false],
    ["CodeableConcept", "category", true],
    ["CodeableReference", "code", false],
    ["boolean", "doNotPerform", false],
    ["Reference", "encounter", false],
    ["Reference", "focus", true],
    ["Identifier", "identifier", true],
    ["canonical", "instantiatesCanonical", true],
    ["uri", "instantiatesUri", true],
    ["code", "intent", false],
    ["CodeableReference", "location", true],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["Timing", "occurrenceTiming", false],
    ["Reference", "performer", true],
    ["CodeableConcept", "performerType", false],
    ["code", "priority", false],
    ["Quantity", "quantityQuantity", false],
    ["Ratio", "quantityRatio", false],
    ["Range", "quantityRange", false],
    ["CodeableReference", "reason", true],
    ["Reference", "replaces", true],
    ["Reference", "requester", false],
    ["Identifier", "requisition", false],
    ["Reference", "specimen", true],
    ["code", "status", false],
    ["Reference", "subject", false],
  ],
  Slot: [
    ["CodeableConcept", "appointmentType", true],
    ["instant", "end", false],
    ["Identifier", "identifier", true],
    ["Reference", "schedule", false],
    ["CodeableConcept", "serviceCategory", true],
    ["CodeableReference", "serviceType", true],
    ["CodeableConcept", "specialty", true],
    ["instant", "start", false],
    ["code", "status", false],
  ],
  Specimen: [
    ["Identifier", "accessionIdentifier", false],
    ["code", "combined", false],
    ["CodeableConcept", "condition", true],
    ["Identifier", "identifier", true],
    ["dateTime", "receivedTime", false],
    ["code", "status", false],
    ["Reference", "subject", false],
    ["CodeableConcept", "type", false],
  ],
  SpecimenDefinition: [
    ["CodeableConcept", "collection", true],
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["canonical", "derivedFromCanonical", true],
    ["uri", "derivedFromUri", true],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", false],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["CodeableConcept", "patientPreparation", true],
    ["string", "publisher", false],
    ["code", "status", false],
    ["CodeableConcept", "subjectCodeableConcept", false],
    ["Reference", "subjectReference", false],
    ["string", "timeAspect", false],
    ["string", "title", false],
    ["CodeableConcept", "typeCollected", false],
    ["uri", "url", false],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  StructureDefinition: [
    ["boolean", "abstract", false],
    ["canonical", "baseDefinition", false],
    ["ContactDetail", "contact", true],
    ["string", "contextInvariant", true],
    ["dateTime", "date", false],
    ["code", "derivation", false],
    ["boolean", "experimental", false],
    ["code", "fhirVersion", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["Coding", "keyword", true],
    ["code", "kind", false],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "type", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  StructureMap: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["canonical", "import", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  Subscription: [
    ["Coding", "channelType", false],
    ["ContactPoint", "contact", true],
    ["code", "content", false],
    ["code", "contentType", false],
    ["instant", "end", false],
    ["url", "endpoint", false],
    ["unsignedInt", "heartbeatPeriod", false],
    ["Identifier", "identifier", true],
    ["Reference", "managingEntity", false],
    ["positiveInt", "maxCount", false],
    ["string", "name", false],
    ["string", "reason", false],
    ["code", "status", false],
    ["unsignedInt", "timeout", false],
    ["canonical", "topic", false],
  ],
  SubscriptionStatus: [
    ["CodeableConcept", "error", true],
    ["integer64", "eventsSinceSubscriptionStart", false],
    ["code", "status", false],
    ["Reference", "subscription", false],
    ["canonical", "topic", false],
    ["code", "type", false],
  ],
  SubscriptionTopic: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["canonical", "derivedFrom", true],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  Substance: [
    ["CodeableConcept", "category", true],
    ["CodeableReference", "code", false],
    ["markdown", "description", false],
    ["dateTime", "expiry", false],
    ["Identifier", "identifier", true],
    ["boolean", "instance", false],
    ["Quantity", "quantity", false],
    ["code", "status", false],
  ],
  SubstanceDefinition: [
    ["CodeableConcept", "classification", true],
    ["markdown", "description", false],
    ["CodeableConcept", "domain", false],
    ["CodeableConcept", "grade", true],
    ["Identifier", "identifier", true],
    ["Reference", "informationSource", true],
    ["Reference", "manufacturer", true],
    ["Annotation", "note", true],
    ["Reference", "nucleicAcid", false],
    ["Reference", "polymer", false],
    ["Reference", "protein", false],
    ["Reference", "referenceInformation", false],
    ["CodeableConcept", "status", false],
    ["Reference", "supplier", true],
    ["string", "version", false],
  ],
  SubstanceNucleicAcid: [
    ["string", "areaOfHybridisation", false],
    ["integer", "numberOfSubunits", false],
    ["CodeableConcept", "oligoNucleotideType", false],
    ["CodeableConcept", "sequenceType", false],
  ],
  SubstancePolymer: [
    ["CodeableConcept", "class", false],
    ["CodeableConcept", "copolymerConnectivity", true],
    ["CodeableConcept", "geometry", false],
    ["Identifier", "identifier", false],
    ["string", "modification", false],
  ],
  SubstanceProtein: [
    ["string", "disulfideLinkage", true],
    ["integer", "numberOfSubunits", false],
    ["CodeableConcept", "sequenceType", false],
  ],
  SubstanceReferenceInformation: [["string", "comment", false]],
  SubstanceSourceMaterial: [
    ["CodeableConcept", "countryOfOrigin", true],
    ["CodeableConcept", "developmentStage", false],
    ["string", "geographicalLocation", true],
    ["Identifier", "organismId", false],
    ["string", "organismName", false],
    ["Identifier", "parentSubstanceId", true],
    ["string", "parentSubstanceName", true],
    ["CodeableConcept", "sourceMaterialClass", false],
    ["CodeableConcept", "sourceMaterialState", false],
    ["CodeableConcept", "sourceMaterialType", false],
  ],
  SupplyDelivery: [
    ["Reference", "basedOn", true],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["Timing", "occurrenceTiming", false],
    ["Reference", "partOf", true],
    ["code", "status", false],
  ],
  SupplyRequest: [
    ["dateTime", "authoredOn", false],
    ["Reference", "basedOn", true],
    ["CodeableConcept", "category", false],
    ["Identifier", "identifier", true],
    ["CodeableReference", "item", false],
    ["dateTime", "occurrenceDateTime", false],
    ["Period", "occurrencePeriod", false],
    ["Timing", "occurrenceTiming", false],
    ["code", "priority", false],
    ["Quantity", "quantity", false],
    ["Reference", "requester", false],
    ["code", "status", false],
    ["Reference", "supplier", true],
  ],
  Task: [
    ["Reference", "basedOn", true],
    ["CodeableConcept", "businessStatus", false],
    ["CodeableConcept", "code", false],
    ["string", "description", false],
    ["boolean", "doNotPerform", false],
    ["Reference", "encounter", false],
    ["Period", "executionPeriod", false],
    ["Reference", "focus", false],
    ["Reference", "for", false],
    ["Identifier", "groupIdentifier", false],
    ["canonical", "instantiatesCanonical", false],
    ["uri", "instantiatesUri", false],
    ["code", "intent", false],
    ["dateTime", "lastModified", false],
    ["Reference", "location", false],
    ["Reference", "owner", false],
    ["Reference", "partOf", true],
    ["Period", "requestedPeriod", false],
    ["Reference", "requester", false],
    ["code", "status", false],
    ["CodeableReference", "statusReason", false],
  ],
  TerminologyCapabilities: [
    ["ContactDetail", "contact", true],
    ["markdown", "copyright", false],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["code", "kind", false],
    ["boolean", "lockedDate", false],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  TestPlan: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  TestReport: [
    ["Identifier", "identifier", false],
    ["dateTime", "issued", false],
    ["string", "name", false],
    ["code", "result", false],
    ["decimal", "score", false],
    ["code", "status", false],
    ["string", "tester", false],
    ["canonical", "testScript", false],
  ],
  TestScript: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  Transport: [
    ["Reference", "basedOn", true],
    ["CodeableConcept", "code", false],
    ["dateTime", "completionTime", false],
    ["Reference", "currentLocation", false],
    ["string", "description", false],
    ["Reference", "encounter", false],
    ["Reference", "focus", false],
    ["Reference", "for", false],
    ["Identifier", "groupIdentifier", false],
    ["canonical", "instantiatesCanonical", false],
    ["uri", "instantiatesUri", false],
    ["code", "intent", false],
    ["dateTime", "lastModified", false],
    ["Reference", "location", false],
    ["Reference", "owner", false],
    ["Reference", "partOf", true],
    ["Reference", "requestedLocation", false],
    ["Reference", "requester", false],
    ["code", "status", false],
    ["CodeableConcept", "statusReason", false],
  ],
  ValueSet: [
    ["ContactDetail", "contact", true],
    ["dateTime", "date", false],
    ["Period", "effectivePeriod", false],
    ["boolean", "experimental", false],
    ["Identifier", "identifier", true],
    ["boolean", "immutable", false],
    ["CodeableConcept", "jurisdiction", true],
    ["string", "name", false],
    ["string", "publisher", false],
    ["code", "status", false],
    ["string", "title", false],
    ["uri", "url", false],
    ["UsageContext", "useContext", true],
    ["string", "version", false],
    ["string", "versionAlgorithmString", false],
    ["Coding", "versionAlgorithmCoding", false],
  ],
  VerificationResult: [
    ["CodeableConcept", "failureAction", false],
    ["CodeableConcept", "need", false],
    ["code", "status", false],
    ["dateTime", "statusDate", false],
    ["Reference", "target", true],
    ["string", "targetLocation", true],
    ["CodeableConcept", "validationProcess", true],
    ["CodeableConcept", "validationType", false],
  ],
  VisionPrescription: [
    ["dateTime", "created", false],
    ["dateTime", "dateWritten", false],
    ["Reference", "patient", false],
    ["Reference", "prescriber", false],
    ["code", "status", false],
  ],
};

export interface NarrativeOptions {
  /** The formatter to use. Will use the `Formatter.default` if not provided. */
  formatter?: DefaultFormatter | null | undefined;
}

export function narrative<TResource extends AnyDomainResource>(
  resource: TResource,
  options?: NarrativeOptions | null | undefined
): Narrative | undefined {
  const generator = NARRATIVE_GENERATORS[resource.resourceType];
  if (!generator) {
    return;
  }

  if (typeof generator === "function") {
    const result = generator(resource);
    if (typeof result === "string") {
      return {
        status: "generated",
        div: result,
      };
    }

    return result;
  }

  return {
    status: "generated",
    div: `<div xmlns="http://www.w3.org/1999/xhtml">${render(
      resource,
      generator,
      options
    )}</div>`,
  };
}

function render(
  item: object,
  components: Array<NarrativeItemGenerator>,
  options: NarrativeOptions | null | undefined
): string {
  const formatter = options?.formatter ?? Formatter.default;

  return `<ul>${components
    .map((component) => {
      const [type, attribute] = component;
      const value = (item as any)[attribute];

      if (value == undefined) {
        return;
      }

      let renderedValue;
      const narrativeGenerator = NARRATIVE_GENERATORS[type];
      if (typeof narrativeGenerator === "function") {
        renderedValue = narrativeGenerator(value);
      } else if (typeof narrativeGenerator === "object") {
        renderedValue = render(value, narrativeGenerator, options);
      } else if (formatter.canFormat(type)) {
        renderedValue = htmlEncode(formatter.format(type, value as never));
      } else {
        return;
      }

      return `<li><span>${startCase(attribute).replace(
        " Boolean",
        ""
      )}: </span>${renderedValue}</li>`;
    })
    .filter(Boolean)
    .join("")}</ul>`;
}

function htmlEncode(value: string): string {
  return value.replace(
    /[&<>\u00A0-\u9999]/g,
    (i) => "&#" + i.codePointAt(0) + ";"
  );
}
