import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FhirUiProviderClientWrapper } from "./FhirUiProviderClientWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <FhirUiProviderClientWrapper>
        <body className={inter.className}>{children}</body>
      </FhirUiProviderClientWrapper>
    </html>
  );
}
